### ISSUE TITLE
Designer: Calculated node path is invalid.

### ISSUE THREAD

**Issue by zlatanov** [dotnet/wpf#1029]
* .NET Core Version: 3.0.0-preview6-27804-01
* Windows version: 1903
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**
The designer throws InvalidOperationException:

```
Calculated node path is invalid -- null->MavUserControl:MavUserControl,ManagedLocalProperty: System.Collections.DictionaryEntry.Value->ControlTemplate:ContentPresenter,System.Object.ViewNodeSourceContainer: Object->MavUserControl:ListBox,ManagedLocalProperty: System.Collections.DictionaryEntry.Value->ControlTemplate:ScrollViewer,ManagedLocalProperty: System.Collections.DictionaryEntry.Value->ControlTemplate:Setter,ManagedLocalProperty: System.Windows.Setter.Value->ControlTemplate:Grid
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.InstanceBuilders.IsolatedSurfaceInstanceManager.GetCorrespondingNodePath(IViewNode viewNode)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.GetCorrespondingSceneElement(IViewObject viewObject)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.FilterPotentialHit(IViewObject viewObject)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.GetFilterBehavior(IViewObject potentialHitTestTarget)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.GetFilterBehavior(IViewObject potentialHitTestTarget)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.GetFilterBehavior(IViewObject potentialHitTestTarget)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.GetFilterBehavior(IViewObject potentialHitTestTarget)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.GetFilterBehavior(IViewObject potentialHitTestTarget)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.<PerformHitTest>d__15.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable1 source)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlSceneView.GetElementAtPoint(Point point, HitTestModifier hitTestModifier, InvisibleObjectHitTestModifier invisibleObjectHitTestModifier, ICollection1 ignoredElements)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlSceneView.HitElementHelper.GetSelectableElementAtPoint(Point point)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlSceneView.GetSelectableElementAtPoint(Point point, SelectionFor3D selectionFor3D, Boolean selectedOnly, Boolean smartInvisiblePanelSelect, Boolean isDrillingEnabled)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Views.SceneView.GetCachedSelectableElementAtPoint(Point point, SelectionFor3D selectionFor3D, Boolean isDrillingEnabled)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Tools.ToolBehavior.CachedHitTest(Point pointerPosition, Boolean allowDrilling)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Tools.Selection.ElementEditorBehavior.OnHoverOverNonAdorner(Point pointerPosition)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Tools.ElementToolBehavior.OnHover(Point pointerPosition)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Tools.EventRouter.ScopeElement_MouseMove_Internal(MouseEventArgs args)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Tools.EventRouter.<>c__DisplayClass59_0.<ScopeElement_MouseMoveCore>b__1()
   at Microsoft.VisualStudio.DesignTools.Utility.ProtectionZone.TrueProtectionZone.Execute(Action action)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

The project where this happens is quite big. Let me know if the exception stack trace is not enough to reason about the problem and I will try to make a minimal repo project.

**Comment by grubioe** [comment]
@LyalinDotCom can you take a look?

**Comment by grubioe** [comment]
Hi @zlatanov  can you log an issue in the Visual Studio Developer Community- it will then be directed to the Designer team.  
https://developercommunity.visualstudio.com/content/problem/post.html?space=8

Thanks!
