### ISSUE TITLE
NRE in Automation Peers

### ISSUE THREAD

**Issue by onovotny** [dotnet/wpf#122]
.NET Core 3 preview 1

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Automation.Peers.ItemAutomationPeer.GetNameCore()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(object arg)
   at System.Windows.Media.MediaContext+InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(ref MSG msg)
   at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(ref MSG msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at PackageExplorer.App.Main()
```

**Comment by rladuca** [comment]
@miguep Will this be part of the remaining diff of desktop framework 4.8 to .NET Core 3?

**Comment by miguep** [comment]
@rladuca it is not part of that work

**Comment by onovotny** [comment]
I'm seeing a lot of these happen still, any reason this can't be looked at for 3.0?

**Comment by miguep** [comment]
We've observed this failure in .NET Framework as well and do not believe this is new to Core.

The WPF team's focus currently is on ensuring functional and performance parity between WPF in .NET Core and .NET Framework, once we meet that goal we can start looking into fixing some of these bugs

**Comment by weltkante** [comment]
Maybe quantify what "a lot" means. If the exception is rare in Desktop Framework and common in Core Framework that would still be a regression (in my opinion).

**Comment by MarkWatts12** [comment]
Seeing the same issue here.  WPF (Framework 4.8 and 4.7.2)  Same stack trace more or less.  Can't find the culprit.

**Comment by eriove** [comment]
I suddenly started to get this every 2 seconds instead of once every other day of using the program. I turned on Frameworks source code debugging and the code fails on `else if (item != null)` in [ItemAutomationPeer.GetNameCore()](https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemAutomationPeer.cs#L484)

![image](https://user-images.githubusercontent.com/9482927/91034580-83e0e380-e605-11ea-8267-ac774e198f3d.png)

Yes, that's a null reference exception on the line that checks if an object is null.

Not much else can be seen in the debugger. Here are the local variables
![image](https://user-images.githubusercontent.com/9482927/91034762-d0c4ba00-e605-11ea-9bd1-0bc74f093835.png)

Most notably `item` is a [`MS.Internal.NamedObject`](https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/NamedObject.cs) with the value `"{DependencyProperty.UnsetValue}"`.

I really can't understand throw at that line. I suspect the symbols, binary and source are out of sync.

**Comment by KirillOsenkov** [comment]
The nullref is because the ItemsControlAutomationPeer is null:

![image](https://user-images.githubusercontent.com/679326/192119884-0961d7aa-cc60-4ce2-8a1d-23e2efdce533.png)

**Comment by KirillOsenkov** [comment]
This is during scrolling of a virtualized tree view when the peer tree view item has been scrolled away and there's no container matching the peer item.

Here's a more relevant stack where ContainerFromItem returns null for an item, which propagates all the way down to ItemsControlAutomationPeer property which returns null and throws.

<HTML>
<BODY>
<TABLE><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>ItemContainerGenerator.ContainerFromItem Line 605</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>ItemAutomationPeer.GetWrapper Line 104</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>ItemAutomationPeer.GetWrapperPeer Line 114</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>TreeViewDataItemAutomationPeer.GetWrapperPeer Line 83</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>TreeViewDataItemAutomationPeer.GetItemsControlAutomationPeer Line 122</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>ItemAutomationPeer.get_ItemsControlAutomationPeer Line 693</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>ItemAutomationPeer.GetWrapper Line 92</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>ItemAutomationPeer.GetWrapperPeer Line 114</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>TreeViewDataItemAutomationPeer.GetWrapperPeer Line 83</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>TreeViewItemAutomationPeer.iterate Line 123</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>TreeViewItemAutomationPeer.iterate Line 145</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>TreeViewItemAutomationPeer.iterate Line 145</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>TreeViewItemAutomationPeer.iterate Line 145</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>TreeViewItemAutomationPeer.GetChildrenCore Line 68</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>AutomationPeer.EnsureChildren Line 1402</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>AutomationPeer.ForceEnsureChildren Line 1422</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationFramework</TD><TD>ItemAutomationPeer.GetChildrenCore Line 203</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>AutomationPeer.EnsureChildren Line 1402</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>AutomationPeer.UpdateChildrenInternal Line 1815</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>AutomationPeer.UpdateChildren Line 1927</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>AutomationPeer.UpdateSubtree Line 2017</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>AutomationPeer.UpdateSubtree Line 2021</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>AutomationPeer.UpdateSubtree Line 2021</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>AutomationPeer.UpdateSubtree Line 2021</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>AutomationPeer.UpdateSubtree Line 2021</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>AutomationPeer.UpdateSubtree Line 2021</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>AutomationPeer.FireAutomationEvents Line 1784</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>ContextLayoutManager.fireAutomationEvents Line 728</TD></TR><TR><TD>&nbsp;</TD><TD>PresentationCore</TD><TD>ContextLayoutManager.UpdateLayout Line 425</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by KirillOsenkov** [comment]
This line is clearly missing a null check for ItemsControlAutomationPeer:
https://github.com/dotnet/wpf/blob/03a85c0a3a35d22fdff9cb31bc40a41eb91e5af6/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemAutomationPeer.cs#L532

**Comment by KirillOsenkov** [comment]
To clarify: the peer that has its ItemsControlAutomationPeer null is:
`System.Windows.Automation.Peers.TreeViewDataItemAutomationPeer`

**Comment by KirillOsenkov** [comment]
I'm guessing to work around this we should ensure each tree view item has a derived automation peer that overrides GetNameCore() to check for ItemsControlAutomationPeer being null and just return a dummy string then?

**Comment by KirillOsenkov** [comment]
This is a more impactful issue in WPF that impacts a lot of customers. Simple web search for ItemAutomationPeer.GetNameCore() will result in a lot of hits and a lot of people seeing this.

We need to service .NET Framework 4.8 with this fix after testing.
