### ISSUE TITLE
UIAutomation could not load dll

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/wpf#124]
Saw this twice in my telemetry

```
System.TypeInitializationException: The type initializer for 'System.Windows.Automation.Peers.AutomationPeer' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Automation.TextPatternIdentifiers' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'UIAutomationCore.dll' or one of its dependencies: The paging file is too small for this operation to complete. (Exception from HRESULT: 0x800705AF)
   at MS.Internal.Automation.UiaCoreTypesApi.RawUiaGetReservedMixedAttributeValue(out object mixedAttributeValue)
   at MS.Internal.Automation.UiaCoreTypesApi.UiaGetReservedMixedAttributeValue()
   at System.Windows.Automation.TextPatternIdentifiers..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Automation.Peers.AutomationPeer.Initialize()
   at System.Windows.Automation.Peers.AutomationPeer..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Automation.Peers.AutomationPeer.RaiseFocusChangedEventHelper(IInputElement newFocus)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, int timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, bool askOld, bool askNew, bool forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, bool askOld, bool askNew, bool forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.Input.Keyboard.Focus(IInputElement element)
   at System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
   at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, ref bool handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, object arg)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
```

**Comment by anti-matter** [comment]
We have hundreds of reports of this in our telemetry. Was here about a new issue when I saw this one already exists.

```2020/11/09 21:54:29.565|FATAL|System.TypeInitializationException: The type initializer for 'System.Windows.Automation.Peers.AutomationPeer' threw an exception.
 ---> System.IO.FileNotFoundException: 
File name: 'UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Windows.Automation.Peers.AutomationPeer.Initialize()
   at System.Windows.Automation.Peers.AutomationPeer..cctor()


   --- End of inner exception stack trace ---
   at System.Windows.Automation.Peers.AutomationPeer.RaiseFocusChangedEventHelper(IInputElement newFocus)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
   at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) The type initializer for 'System.Windows.Automation.Peers.AutomationPeer' threw an exception.|Warp.UI.App|
```
This happens for some users when we show our main window. Our app is packaged as a standalone using .Net Core 3.1. In the publish folder, we see the UIAutomation.dll is being included, so not sure what we can do to fix this.

Please help!

**Comment by chucker** [comment]
Is it possible that `UIAutomationCore.dll` is among the first dependencies WPF tries to load?

I tried running a single-file .NET Core 3.1 app from a network drive, and after wake from standby, I got:

    System.DllNotFoundException: Unable to load DLL 'UIAutomationCore.dll' or one of its dependencies. The network path was not found.

Note that the DLL doesn't actually seem to exist:

* the network drive, of course, doesn't contain it (because the exe is self-contained)
* _nor_ does the temporary path created locally (inside `%temp%\.net`)
* nor does the `Microsoft.WindowsDesktop.App` runtime dir — it contains `UIAutomationClient.dll` and a few others, but not Core

Nonetheless, it apparently briefly probes (and fails to) the network drive.

**Comment by singhashish-wpf** [comment]
We'll need some repro or dump to check this further. Closing this as of now.
