### ISSUE TITLE
.NET Core 3 / WPF: SEHException's

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/wpf#125]
I'm seeing SEHException's from .NET Core 3 preview 1:

They all have the following stack trace. Windows 10 17134, 17763

Not sure what repo this belongs with as it starts with `Microsoft.Win32.CommonDialog.ShowDialog()`

```
System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at MS.Internal.AppModel.IFileDialog.Show(IntPtr parent)
   at Microsoft.Win32.FileDialog.RunVistaDialog(IntPtr hwndOwner)
   at Microsoft.Win32.FileDialog.RunDialog(IntPtr hwndOwner)
   at Microsoft.Win32.CommonDialog.ShowDialog()
   at PackageExplorer.UIServices.OpenSaveFileDialog(string title, string defaultFileName, string initialDirectory, string filter, bool overwritePrompt, out string selectedFilePath, out int selectedFilterIndex) in PackageExplorer\MefServices\UIServices.cs:line 36
   at PackageExplorerViewModel.SavePackageCommand.SaveAs() in PackageViewModel\Commands\SavePackageCommand.cs:line 151
   at PackageExplorerViewModel.SavePackageCommand.Execute(object parameter) in PackageViewModel\Commands\SavePackageCommand.cs:line 96
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, bool userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(ref MSG msg)
   at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(ref MSG msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at PackageExplorer.App.Main()
```

**Comment by vatsan-madhavan** [comment]
Is there a way to reproduce this, or perhaps a crash dump?

**Comment by onovotny** [comment]
WER may have dumps; I've had many hits on this in the NuGet Package Explorer telemetry.

**Comment by rladuca** [comment]
I was unable to find any crashes associated with .NET 4.8 that were similar to this.  This looks to be solely a .NET Core 3 issue.

**Comment by singhashish-wpf** [comment]
Closing in absence of any repro or trace.
