### ISSUE TITLE
OOM: Pen Input

### ISSUE THREAD

**Issue by onovotny** [dotnet/wpf#126]
From telemetry, unhandled exception:

```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at MS.Win32.Penimc.IPimcManager2.GetTablet(uint tablet, out IPimcTablet2 IPimcTablet)
   at System.Windows.Input.PenThreadWorker+WorkerOperationGetTabletsInfo.OnDoWork()
   at System.Windows.Input.PenThreadWorker+WorkerOperation.DoWork()
   at System.Windows.Input.PenThreadWorker.ThreadProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by rladuca** [comment]
@onovotny Thanks for bringing this up.  Does your telemetry contain OS version and .NET version?  It would be good if you could fill out the bug template with that information so we can properly categorize and do faster searches for related fixes or issues.

This bug was actually an issue with the underlying ink library (WISP) that WPF uses for touch and stylus input.  It was a Windows fix that is available in the latest updates of Windows 10 version 1709 (Fall Creators Update) and above.

From the data I can see in crashes, NuGetPackageExplorer seems to be seeing this on some Windows 8.1 machines that don't have the update.  So I am going to close this one as fixed.

**Comment by onovotny** [comment]
Info:

```
hostname
INUH100187
locale
en-IN
osName
Microsoft Windows NT 6.2.9200.0
time
2018-12-06T11:13:14.184Z
timezone
(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi
```
