### ISSUE TITLE
WindowChrome System.OverflowException:“Arithmetic operation resulted in an overflow.”

### ISSUE THREAD

**Issue by xianyun666** [dotnet/wpf#1269]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Windows version: (`winver`)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No
Yes,All .NET Framework 
 
 
 **Problem description:**
 In the case of two monitors，Order: main display 1 below, secondary display 2 above，And the resulting platform is x64，Drag the program to screen 2，A mouse click triggers this exception.
System.OverflowException:“Arithmetic operation resulted in an overflow.”
 **Actual behavior:** 
 System.OverflowException
  HResult=0x80131516
  Message=Arithmetic operation resulted in an overflow.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Shell.WindowChromeWorker._HandleNCHitTest(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

 **Expected behavior:**
 Expect no exceptions, at least not crashes
 **Minimal repro:**
 Look at:
 https://stackoverflow.com/questions/50282355/why-does-my-wpf-application-crash-when-i-bump-my-mousewheel/50282356#50282356
https://developercommunity.visualstudio.com/content/problem/167357/overflow-exception-in-windowchrome.html

**Comment by yanlinsun** [comment]
I encounter the same issue. I have two monitors, the main one is below the second.
If I set the main one above the second, no issues.
[https://github.com/dnGrep/dnGrep/issues/418](url)

**Comment by nick-beer** [comment]
We're also seeing customer reports of this issue via telemetry.
