### ISSUE TITLE
MS.Internal.FontCache.Util' threw an exception. ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by onovotny** [dotnet/wpf#197]
From Telemetry

.NET Core 3.0 Preview 1
Windows 7: Microsoft Windows 6.1.7601 Service Pack 1
locale: en-US

```
System.Windows.Markup.XamlParseException: Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.FrameworkElement' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Documents.TextElement' threw an exception. ---> System.TypeInitializationException: The type initializer for 'MS.Internal.FontCache.Util' threw an exception. ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(string uri, bool dontEscape, UriKind uriKind)
   at System.Uri..ctor(string uriString, UriKind uriKind)
   at MS.Internal.FontCache.Util..cctor()
   --- End of inner exception stack trace ---
   at MS.Internal.FontCache.Util.get_Dpi()
   at System.Windows.SystemParameters.get_Dpi()
   at System.Windows.SystemFonts.ConvertFontHeight(int height)
   at System.Windows.SystemFonts.get_MessageFontSize()
   at System.Windows.Documents.TextElement..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.FrameworkElement..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.FrameworkElement.FindResourceFromAppOrSystem(object resourceKey, out object source, bool disableThrowOnResourceNotFound, bool allowDeferredResourceReference, bool mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(IServiceProvider serviceProvider, bool allowDeferredReference, bool mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.FindResourceInEnviroment(IServiceProvider serviceProvider, bool allowDeferredReference, bool mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.TryProvideValueImpl(IServiceProvider serviceProvider, bool allowDeferredReference, bool mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.TryProvideValueInternal(IServiceProvider serviceProvider, bool allowDeferredReference, bool mustReturnDeferredResourceReference)
   at System.Windows.ResourceDictionary.SetOptimizedStaticResources(IList<T> staticResources, IServiceProvider serviceProvider, StaticResourceExtension staticResourceWorker)
   at System.Windows.ResourceDictionary.SetKeys(IList<T> keyCollection, IServiceProvider serviceProvider)
   at System.Windows.ResourceDictionary.SetDeferrableContent(DeferrableContent deferrableContent)
   at System.Windows.ResourceDictionary.set_DeferrableContent(DeferrableContent value)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext+<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__297_0(object target, object value)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(object instance, object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, object obj, object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(object inst, XamlMember property, object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, bool skipJournaledProperties, object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, bool skipJournaledProperties, object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, object parent, bool closeStream)
   at System.Windows.Application.LoadComponent(object component, Uri resourceLocator)
   at PackageExplorer.App.InitializeComponent() in PackageExplorer\App.xaml:line 1
   at PackageExplorer.App.Main()
```

**Comment by GeertvanHorrik** [comment]
Is it me or are most sources not yet available for WPF? Would love to actually contribute some things I encounter, but couldn't find the source code so far.

**Comment by thomasclaudiushuber** [comment]
@GeertvanHorrik The team just started with System.Xaml. The rest is not open source yet. Take a look at the roadmap here: https://github.com/dotnet/wpf/blob/master/roadmap.md

**Comment by stevenbrix** [comment]
Does this only occur on Windows 7? Looks like what is failing is trying to access some environment variable that might not be set on Win7?
