### ISSUE TITLE
Could not locate icon.ico

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#209]
* .NET Core Version: 3.0 Preview1
* Windows version: (`Windows 10 64bit`)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 **Problem description:**

Exception on application start:
IOException: Cannot locate resource 'icon.ico'.

 
 **Actual behavior:**

```
at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
```

 **Expected behavior:**

Start successfully and accept icon path for window like it does in .NET framework.
 
 **Minimal repro:**
 
1. Create new .NET core 3.0 WPF project
2. Right click on project -> properties -> "Icon and manifest" select an .ICO for the application. The selected icon file is now placed into root directory of the project
3. On MainWindow.xaml add this line for window
`Icon="icon.ico"`

[IconIssue.zip](https://github.com/dotnet/wpf/files/2707672/IconIssue.zip)

**Comment by Berrysoft** [comment]
Add
``` xml
  <ItemGroup>
    <None Remove="icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="icon.ico" />
  </ItemGroup>
```
between `<Project>` and `</Project>` in the csproj, or set "Build Action" to "Resource" in Properties window in Visual Studio.

**Comment by Symbai** [comment]
Is solved

**Comment by FANMixco** [comment]
It should be fixed in VS2019.

**Comment by GreatFireWall** [comment]
Not work.

![image](https://user-images.githubusercontent.com/4510984/77039450-ef88aa00-69f0-11ea-98b9-c0cfbcfbc453.png)

![image](https://user-images.githubusercontent.com/4510984/77039475-fb746c00-69f0-11ea-8d9e-7428b1cfa2b6.png)

![image](https://user-images.githubusercontent.com/4510984/77039496-03cca700-69f1-11ea-928f-3825206ba497.png)

**Comment by GreatFireWall** [comment]
Ignore me, after `clean` and `rebuild` project, it works.

**Comment by U-C-S** [comment]
I Got this issue in VS2019 16.7.2. 

Added a new icon. didn't like it. So, I deleted it. Then added other icon with a different name.
It gives an error old icon cannot be found. So, I renamed new one to old name. 
Now, it's giving the same error for new icon😑.
