### ISSUE TITLE
Publish self-contained configuration

### ISSUE THREAD

**Issue by Gosha24** [dotnet/wpf#2338]
* .NET Core Version: 3.1
* Windows version: 10
 
 **Problem description:**
 
Publish WPF 
Configuration Release|Any CPU
Target FrameWork netcoreapp3.1
Deployment mode self-contained
target-runtime winx64
Publish:
An error occured

19-Dec-19 12:24:09
System.AggregateException: One or more errors occurred. ---> System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__213.MoveNext()
---> (Inner Exception #0) System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---

System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 

The same error was mentioned in StackOverflow. I deleted Profile and create new one nothing helps

**Comment by rladuca** [comment]
@Gosha24 I was able to publish netcoreapp3.1 x64 self-contained from both Visual Studio and dotnet command line when using a basic WPF project.

Can you give us a minimal project that reproduces the issue for you?

**Comment by DennisBaberich** [comment]
I ran into the same problem. Upgrading System.Net.NameResolution to 4.3.0 helped.

**Comment by pantonis** [comment]
I have the same issue with VS2019 16.4.3. I can send you a repro project if you wish

**Comment by TiepMesjien** [comment]
Same, well, same settings, same build, however it's version 16.5.5, and all the log tells me is this, which is well, not very helpful (can't seem to find which output log, activity log mentions nothing):

_9-10-2020 14:20:02_
System.AggregateException: One or more errors occurred. ---> System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---

System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 

===================
