### ISSUE TITLE
GetDpiAwarenessCompatibleNotificationWindow exception in Win10 1909

### ISSUE THREAD

**Issue by uecasm** [dotnet/wpf#2486]
I'm experiencing a similar crash as reported in #1953; in my case it's a particular unit test that creates a lot of WPF (and WinForms+ElementHost) windows in sequence and quickly destroys them again.  The unit test is being run from the Resharper plugin inside VS2017 15.9.

Other tests and my main app seem to run ok.  (My main app is DPI Unaware.)

The crash doesn't occur when I run the same test in a different test runner, nor does it happen if I set the Compatibility of the Resharper test runner to DPI Unaware (scaling performed by System).

Is this a regression or is it a related but different issue?  Or did the patch somehow miss this version?  Windows Update says I'm up to date.

* .NET Framework Version: 4.8.03752
* Windows version: Win10 1909 (18363.592)

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Windows.SystemResources.GetDpiAwarenessCompatibleNotificationWindow(HandleRef hwnd)
   at System.Windows.Interop.HwndHost.BuildOrReparentWindow()
   at System.Windows.Interop.HwndHost.OnSourceChanged(Object sender, SourceChangedEventArgs e)
   at System.Windows.SourceChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.PresentationSource.UpdateSourceOfElement(DependencyObject doTarget, DependencyObject doAncestor, DependencyObject doOldParent)
   at System.Windows.PresentationSource.RootChanged(Visual oldRoot, Visual newRoot)
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.Dispose(Boolean disposing)
   at System.Windows.Interop.HwndSource.OnHwndDisposed(Object sender, EventArgs args)
   at MS.Win32.HwndWrapper.Dispose(Boolean disposing, Boolean isHwndBeingDestroyed)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by vatsan-madhavan** [comment]
This is the same as #2089. 

Please try the [.NET Framework January Preview of Quality Rollup](https://devblogs.microsoft.com/dotnet/net-framework-january-preview-of-quality-rollup/) and let us know if it resolves your issue.

**Comment by uecasm** [comment]
@vatsan-madhavan I had previously found that update, but it does not appear to be available for Win10 1909.

I tried downloading 4534131 anyway but it just said "this update is not applicable".

**Comment by uecasm** [comment]
Also FYI, I can't even use `SetProcessDpiAwareness` to disable DPI Awareness on the test runner to work around this crash (as was advised elsewhere), since it returns `E_ACCESSDENIED` since apparently this is a write-once setting.

Since I am not in control of the test runner's manifest, the only workaround that appears to work is to use the Compatibility settings.  (Also, for reasons not fully understood, in Win10 the Compatibility tab does not always appear -- for example I can see it on the test runner exe but not on VS2017's devenv.  Fortunately in this case I don't actually need to set it on the latter, but this seems like a Win10 bug.)

**Comment by uecasm** [comment]
FYI, `SetThreadDpiAwarenessContext(-1)` returns `0x80000022` (which isn't null, so I assume it succeeded), but this does not bypass the exception.

**Comment by vatsan-madhavan** [comment]
@BrettLopez Was the Jan preview rollup released for 1909? 

`SetThreadDpiAwarenessContext `has to be called in the right thread just before `HWND `creation, and you have to ensure that another instance of `SetThreadDpiAwarenessContext `doesn't get called after you and override your intention. This may not be as easy as one might imagine as you've learned - esp. from a test process. This sort of workaround is intended for application developers who are in full control of the stack. 

You can also try to use the [Application Compatibility settings](https://blogs.windows.com/windowsexperience/2017/01/09/announcing-windows-10-insider-preview-build-15002-pc/#B4p617eIRYORoHM1.97) for the app and run it in 'System' or 'System (Enhanced)' mode temporarily until you get the fix.

**Comment by vatsan-madhavan** [comment]
This fix has been released as part of [.NET Framework February 2020 Security and Quality Rollup](https://devblogs.microsoft.com/dotnet/net-framework-february-2020-security-and-quality-rollup/)
