### ISSUE TITLE
SourceColection getting garbage collected for ListCollectionView on switching views

### ISSUE THREAD

**Issue by garghimanshu0786** [dotnet/wpf#2512]
**Problem description:**

While using the same ListCollectionView on different view, the same gets 'DetachedFromSourceCollection' on switching the view.

 **Actual behavior:**

 Void RestoreLiveShaping()
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Data.ListCollectionView.RestoreLiveShaping()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
******** Stack Trace *********

******** BaseStack Trace *********   at System.Windows.Data.ListCollectionView.RestoreLiveShaping()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
 **Expected behavior:**
 User should be able to use a ListCollectionView on different views.

 **Minimal repro:**

1. Create a listcollectionview from a new collectionviewsource.
2. Add live filtering properties to the collectionviewsource and set 'IsLiveFiltering' to true.
3. Change that property from another view.
4. Switch from that view to some other view.
5. Change the live filtering property again.
6. The code will crash with the above call stack.

RCA:-
Garbage collector is setting source collection to null on switching to a different view.

**Comment by miloush** [comment]
Do you have a repro project?

**Comment by garghimanshu0786** [comment]
Nope

**Comment by gomathip02** [comment]
@garghimanshu0786 - Pls let us know when you can provide a repro app. We will reopen this bug.
