### ISSUE TITLE
ApiCompat gives command-line syntax errors on build

### ISSUE THREAD

**Issue by wjk** [dotnet/wpf#2530]
* .NET Core Version: 5.0.100-preview.1.20108.3
* Windows version: 10.0.18363.592
* Does the bug reproduce also in WPF for .NET Framework 4.8?: N/A, build issue
 
 **Problem description:**
 
When I try to build WPF from source, ApiCompat complains of an invalid command line and the build fails for this reason.

 **Actual behavior:**

Build should succeed.
 
 **Expected behavior:**

```
Unhandled Exception: McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized command o
  r argument 'D:\Projects\dotnet-wpf\artifacts\bin\System.Xaml-ref\Debug\netcoreapp5.0\,C:\Users\William\.nuget\package
  s\microsoft.codeanalysis.common\2.9.0\lib\netstandard1.3\,C:\Users\William\.nuget\packages\microsoft.netcore.app.ref\
  5.0.0-alpha1.19514.1\ref\netcoreapp5.0\,C:\Users\William\.nuget\packages\system.appcontext\4.3.0\ref\netstandard1.6\,
  C:\Users\William\.nuget\packages\system.collections.immutable\1.5.0\lib\netstandard2.0\,C:\Users\William\.nuget\packa
  ges\system.console\4.3.0\ref\netstandard1.3\,C:\Users\William\.nuget\packages\system.dynamic.runtime\4.3.0\ref\netsta
  ndard1.3\,C:\Users\William\.nuget\packages\system.io.compression\4.3.0\ref\netstandard1.3\,C:\Users\William\.nuget\pa
  ckages\system.io.filesystem\4.3.0\ref\netstandard1.3\,C:\Users\William\.nuget\packages\system.io.filesystem.primitive
  s\4.3.0\ref\netstandard1.3\,C:\Users\William\.nuget\packages\system.linq\4.3.0\ref\netstandard1.6\,C:\Users\William\.
  nuget\packages\system.linq.expressions\4.3.0\ref\netstandard1.6\,C:\Users\William\.nuget\packages\system.reflection.m
  etadata\1.6.0\lib\netstandard2.0\,C:\Users\William\.nuget\packages\system.runtime.handles\4.3.0\ref\netstandard1.3\,C
  :\Users\William\.nuget\packages\system.runtime.numerics\4.3.0\ref\netstandard1.1\,C:\Users\William\.nuget\packages\sy
  stem.security.accesscontrol\5.0.0-alpha1.19512.1\ref\netstandard2.0\,C:\Users\William\.nuget\packages\system.security
  .cryptography.algorithms\4.3.0\ref\netstandard1.6\,C:\Users\William\.nuget\packages\system.security.cryptography.enco
  ding\4.3.0\ref\netstandard1.3\,C:\Users\William\.nuget\packages\system.security.cryptography.primitives\4.3.0\ref\net
  standard1.3\,C:\Users\William\.nuget\packages\system.security.cryptography.x509certificates\4.3.0\ref\netstandard1.4\
  ,C:\Users\William\.nuget\packages\system.security.permissions\5.0.0-alpha1.19512.1\ref\netcoreapp3.0\,C:\Users\Willia
  m\.nuget\packages\system.security.principal.windows\5.0.0-alpha1.19512.1\ref\netcoreapp3.0\,C:\Users\William\.nuget\p
  ackages\system.threading.tasks.extensions\4.3.0\lib\netstandard1.0\,C:\Users\William\.nuget\packages\system.threading
  .tasks.parallel\4.3.0\ref\netstandard1.1\,C:\Users\William\.nuget\packages\system.valuetuple\4.3.0\lib\netstandard1.0
  \,C:\Users\William\.nuget\packages\system.windows.extensions\5.0.0-alpha1.19512.1\ref\netcoreapp3.0\,C:\Users\William
  \.nuget\packages\system.xml.xdocument\4.3.0\ref\netstandard1.3\,'
     at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.HandleUnexpectedArg(String argTypeName, String argVal
  ue)
     at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessCommandOrArgument()
     at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
     at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
     at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
     at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
     at Microsoft.DotNet.ApiCompat.Program.Main(String[] args) in /_/src/Microsoft.DotNet.ApiCompat/Program.cs:line 61
```

 **Minimal repro:**

Build the repo. I am on commit 956b88f3bccf33f45ca7c3206590ddf9322698f2.

Here is a zipped MSBuild binlog: [Build.binlog.zip](https://github.com/dotnet/wpf/files/4176405/Build.binlog.zip)

**Comment by rladuca** [comment]
@wjk Can you try `git clean -xdf` and then rebuilding?  Sometimes old artifacts interact badly with ApiCompat if you've switched branches to different versions, etc.

**Comment by wjk** [comment]
Worked great. Thanks!
