### ISSUE TITLE
WebBrowser crashes with low probability

### ISSUE THREAD

**Issue by orrindeng** [dotnet/wpf#2828]
**OS Version**: Windows 10 Enterprise, 64-bit, build 18363
**.NET Framework**: 4.7.2

**What we do**:
We use a WebBrowser control in our application. The WebBrowser source is a local HTML file. We call WebBrowser.InvokeScript method to generate a canvas on the html page and get the canvas base64 data. Then we use the base64 data to create a bitmap image on WPF application and show it for our end-user. 

**What happens**:
It behaves well at most time. But our application **crashes with low probability**. We found the call stack in Windows Events. 
`Application: Forguncy.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FF936B14B36
Stack:
   at MS.Win32.UnsafeNativeMethods+IDispatchEx.InvokeEx(Int32, Int32, Int32, DISPPARAMS, System.Object ByRef, EXCEPINFO, IServiceProvider)
   at MS.Win32.UnsafeNativeMethods+IDispatchEx.InvokeEx(Int32, Int32, Int32, DISPPARAMS, System.Object ByRef, EXCEPINFO, IServiceProvider)
   at System.Windows.Controls.WebBrowser.InvokeScript(System.String, System.Object[])
   at Forguncy.Common.ListViewPreviewer.InvokeScript(System.String, System.String)
   at Forguncy.Common.ListViewPreviewer+<>c__DisplayClass17_1.<GetListViewPreviewResult>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Forguncy.Program.InitializeMain(System.Action, Boolean)
   at Forguncy.Program.Main(System.String[])`

The exception will make our application crashes. So could you help me to solve it?

**Comment by fabiant3** [comment]
We would need a repro and preferably on .NET Core. Would you be able to provide one?

**Comment by fabiant3** [comment]
Closing for now, feel free to reopen with a repro.
