### ISSUE TITLE
OutOfMemoryException in XamlReader.Parse

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#312]
<p>The following line of code results in the parser getting stuck in a loop, adding simulated `EndMember` and `EndObject` nodes to a list until it eventually throws an `OutOfMemoryException`.</p><p></p><pre>XamlReader.Parse(&quot;&lt;DataTemplate xmlns=\&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation\&quot;&gt;Invalid Markup&lt;/DataTemplate&gt;&quot;);</pre><pre>System.OutOfMemoryException : Array dimensions exceeded supported range.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at System.Xaml.XamlNodeList.Add(XamlNodeType nodeType, Object data)
   at System.Xaml.DeferringWriter.WriteEndMember()
   at System.Xaml.XamlObjectWriter.WriteEndMember()
   at System.Xaml.XamlObjectWriter.Dispose(Boolean disposing)
   at System.Xaml.XamlWriter.System.IDisposable.Dispose()
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader)
   at System.Windows.Markup.XamlReader.Parse(String xamlText)</pre><p></p><p>I understand that the xaml is invalid and would be perfectly happy if it threw a `XamlParseException`, but I think `OutOfMemoryException` is the wrong way to deal with this situation :)</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/439875/outofmemoryexception-in-xamlreaderparse.html
VSTS ticketId: 781519_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by brian-reichle** [comment]
This issue was actually found in the .NET Framework version of WPF, so I'm not sure if it belongs here. Unfortunately I don't have the security rights to seek clarification at the "Developer Community".

**Comment by stevenbrix** [comment]
I'm putting this bug into the Future milestone since it is also present in .NET Framework. The goal for the 3.0 release is functional and performance parity with .NET framework, so once we have validated that we can look into fixing these bugs.
