### ISSUE TITLE
 WPF applications with non ascii project names do not work

### ISSUE THREAD

**Issue by maxbrister** [dotnet/wpf#3330]
* .NET Core Version: 5.0.100-preview.7.20366.6
* Windows version: 2004 (OS Build 19041.450)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/master/README.md#reporting-security-issues-and-security-bugs).
 
 **Problem description:**

 WPF applications with non ascii project names throw an exception when creating MainPage.xaml.

 **Actual behavior:**

Exception has occurred: CLR/System.UriFormatException
An exception of type 'System.UriFormatException' occurred in System.Private.Uri.dll but was not handled in user code: 'Invalid URI: The Authority/Host could not be parsed.'
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(Uri baseUri, Uri relativeUri)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Prj_ヺヸヺヰィヰヷゆモ.MainWindow.InitializeComponent() in C:\Users\mabriste\temp\Prj_ヺヸヺヰィヰヷゆモ\MainWindow.xaml:line 1
   at Prj_ヺヸヺヰィヰヷゆモ.MainWindow..ctor() in C:\Users\mabriste\temp\Prj_ヺヸヺヰィヰヷゆモ\MainWindow.xaml.cs:line 25
 
 **Expected behavior:**
 
 **Minimal repro:**

dotnet new wpf --name "Prj_ヺヸヺヰィヰヷゆモ"
cd "Prj_ヺヸヺヰィヰヷゆモ"
dotnet run

Observe app does not start. To see exception start in a debugger.

**Comment by ryalanms** [comment]
Thanks, @maxbrister.  This is now fixed.
