### ISSUE TITLE
Pressing <Enter> Key While Editing WPF DataGrid

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#3753]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Pressing-Enter-Key-While-Editing-WPF-D/768729)._

---
I am not the only person complaing about this bug (I guess).  At pressing Enter key on any editable cell of WPF DataGrid it generates errors such as ((ArgumentOutOfRangeException in DataGridCellsPanel.BringIndexIntoView)).  To overcome this problem I found a work around solution on the net and I used it which is working fine for me.  The solution is as:

private void Dg_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Return)
            {
                e.Handled = true;
                Dg.CommitEdit();
            }
        }

I think this is a BUG and its the time to fix.

---
#### Feedback Bot on 10/9/2019, 05:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Hash Soft on 10/10/2019, 01:41 AM: 

<p>Even with the work around solution I mentioned in my last message, I got the following error:</p><p>System.ArgumentNullException: 'Value cannot be null. Parameter name: element'</p>

#### Feedback Bot on 11/15/2019, 09:31 AM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
#### Hash Soft solved on 10/10/2019, 01:40 AM, 0 votes: 

<p>Even with the work around solution, I got the following error:</p><p>System.ArgumentNullException: 'Value cannot be null. Parameter name: element'</p><p><strong></strong><u></u><sub></sub><sup></sup></p>

#### Hash Soft solved on 11/16/2019, 04:41 PM, 0 votes: 

<p>What a pity.  Even the solution I mentioned in my initial message does not always work.  And its a bad luck for me and for the other developers if you ignore this bug.  Hope you keep this case opened till a solution is fixed.</p>

**Comment by quarkonium3** [comment]
Yeah wow this is old I ran into it here:
[(https://stackoverflow.com/questions/5237185/argumentoutofrangeexception-in-datagridcellspanel-bringindexintoview-when-pressi/5237548)]
I still have the OnPreviewKeyDown workaround in our code...
I've now started getting the System.ArgumentNullException: 'Value cannot be null. Parameter name: element' problem with this in place too. So this seems to be newer. I don't have a workaround for it either. 

This is the original stacktrace for the index out of range problem:
``` 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Windows.Controls.DataGridCellsPanel.BringIndexIntoView(Int32 index)
   at System.Windows.Controls.Primitives.DataGridCellsPresenter.ScrollCellIntoView(Int32 index)
   at System.Windows.Controls.DataGrid.ScrollCellIntoView(ItemInfo info, DataGridColumn column)
   at System.Windows.Controls.DataGrid.OnEnterKeyDown(KeyEventArgs e)
   at System.Windows.Controls.DataGrid.OnKeyDown(KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

With the PreviewKeyDown workaround, now getting the ArgumentNullException here:
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: element
  Source=PresentationCore
  StackTrace:
   at System.Windows.Automation.Peers.UIElementAutomationPeer.FromElement(UIElement element)
   at System.Windows.Controls.DataGrid.CellAutomationValueHolder.TrackValue()
   at System.Windows.Controls.DataGrid.UpdateCellAutomationValueHolder(DataGridCell cell)
   at System.Windows.Controls.DataGrid.OnExecutedCommitEdit(ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at System.Windows.Controls.DataGrid.EndEdit(RoutedCommand command, DataGridCell cellContainer, DataGridEditingUnit editingUnit, Boolean exitEditMode)
   at System.Windows.Controls.DataGrid.CommitEdit()
   at Risk.Platform.Workbench.Views.Tabs.StructureAggregatePage.AnnualOccurrenceArisOnPreviewKeyDown(Object sender, KeyEventArgs e) 
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
