### ISSUE TITLE
Crash on startup: Height must be non-negative

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/wpf#382]
OS: Microsoft Windows 10.0.17134
WPF: `4.8.27325.3 @BuiltBy: dlab14-DDVSOWINAGE058 @Branch: master @Commit: 24b4ae9332545f7677a8ce2f8916cc2284e31b75`

```
System.ArgumentException: Height must be non-negative.
   at System.Windows.Size.set_Height(double value)
   at System.Windows.Controls.TextBlock.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.VirtualizingStackPanel.MeasureChild(ref IItemContainerGenerator generator, ref IContainItemStorage itemStorageProvider, ref IContainItemStorage parentItemStorageProvider, ref object parentItem, ref bool hasUniformOrAverageContainerSizeBeenSet, ref double computedUniformOrAverageContainerSize, ref double computedUniformOrAverageContainerPixelSize, ref bool computedAreContainersUniformlySized, ref bool hasAnyContainerSpanChanged, ref IList items, ref object item, ref IList children, ref int childIndex, ref bool visualOrderChanged, ref bool isHorizontal, ref Size childConstraint, ref Rect viewport, ref VirtualizationCacheLength cacheSize, ref VirtualizationCacheLengthUnit cacheUnit, ref bool foundFirstItemInViewport, ref double firstItemInViewportOffset, ref Size stackPixelSize, ref Size stackPixelSizeInViewport, ref Size stackPixelSizeInCacheBeforeViewport, ref Size stackPixelSizeInCacheAfterViewport, ref Size stackLogicalSize, ref Size stackLogicalSizeInViewport, ref Size stackLogicalSizeInCacheBeforeViewport, ref Size stackLogicalSizeInCacheAfterViewport, ref bool mustDisableVirtualization, bool isBeforeFirstItem, bool isAfterFirstItem, bool isAfterLastItem, bool skipActualMeasure, bool skipGeneration, ref bool hasBringIntoViewContainerBeenMeasured, ref bool hasVirtualizingChildren)
   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(Size constraint, ref Nullable<T> lastPageSafeOffset, ref List<T> previouslyMeasuredOffsets, ref Nullable<T> lastPagePixelSize, bool remeasure)
   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Controls.ItemsControl.MakeVisible(FrameworkElement container, FocusNavigationDirection direction, bool alwaysAtTopOfViewport)
   at System.Windows.Controls.ItemsControl.MakeVisible(int index, FocusNavigationDirection direction, bool alwaysAtTopOfViewport, out FrameworkElement container)
   at System.Windows.Controls.ItemsControl.NavigateToItem(object item, int elementIndex, ItemNavigateArgs itemNavigateArgs, bool alwaysAtTopOfViewport)
   at System.Windows.Controls.ItemsControl.NavigateToItem(ItemInfo info, ItemNavigateArgs itemNavigateArgs, bool alwaysAtTopOfViewport)
   at System.Windows.Controls.ComboBox+<>c.<OnIsDropDownOpenChanged>b__20_1(object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(ref MSG msg)
   at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(ref MSG msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at PackageExplorer.App.Main()
```

**Comment by stevenbrix** [comment]
Thanks @onovotny for filing this! Is there a repro scenario that we can use? Is this an issue with WPF running on .NET Core 3 or .NET Framework 4.8?

**Comment by onovotny** [comment]
This is on .NET Core 3; I don't have a specific repro, this came from telemetry.

**Comment by stevenbrix** [comment]
Gotcha, thanks. Are you seeing a lot of this? Do you have more information other than a callstack that you could share? Just from looking at the callstack, it's nearly impossible to tell how this happened.

**Comment by onovotny** [comment]
So far, I just see a single hit of this from a week ago.

**Comment by weltkante** [comment]
Assuming the .NET Core implementation didn't change too much, there's only two (non inlined) assignments to `Size.Height` I can see in the [reference source](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/TextBlock.cs,12542c7c9422b8b6)

Since padding can't be negative and the text formatting implementation probably changed in .NET Core I'd guess it could be a bug in the new text formatting code returning negative baseline values in some edge cases?

Just a guess, might be entirely wrong.
