### ISSUE TITLE
WPF apps crashes if a TextBlock.FontFamily is set to a bad font file.

### ISSUE THREAD

**Issue by walterlv** [dotnet/wpf#3987]
* .NET Core Version: 5.0.1
* Windows version: 10.0.19042.685
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**

When setting the `FontFamily` property of a TextBlock to a bad font, the WPF application crashes by a `FileFormatException`.
 
 **Actual behavior:** 

```csharp
System.IO.FileFormatException: Invalid file format.
   at MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32 hr)
   at MS.Internal.Text.TextInterface.Font.CreateFontFace()
   at MS.Internal.Text.TextInterface.Font.AddFontFaceToCache()
   at MS.Internal.Text.TextInterface.Font.GetFontFace()
   at System.Windows.Media.GlyphTypeface..ctor(Font font)
   at MS.Internal.FontFace.PhysicalFontFamily.GetGlyphTypeface(FontStyle style, FontWeight weight, FontStretch stretch)
   at MS.Internal.FontFace.PhysicalFontFamily.MS.Internal.FontFace.IFontFamily.GetTypefaceMetrics(FontStyle style, FontWeight weight, FontStretch stretch)
   at System.Windows.Media.Typeface.ConstructCachedTypeface()
   at System.Windows.Media.Typeface.get_CachedTypeface()
   at System.Windows.Media.Typeface.CheckFastPathNominalGlyphs(CharacterBufferRange charBufferRange, Double emSize, Single pixelsPerDip, Double scalingFactor, Double widthMax, Boolean keepAWord, Boolean numberSubstitution, CultureInfo cultureInfo, TextFormattingMode textFormattingMode, Boolean isSideways, Boolean breakOnTabs, Int32& stringLengthFit)
   at MS.Internal.TextFormatting.SimpleRun.CreateSimpleTextRun(CharacterBufferRange charBufferRange, TextRun textRun, TextFormatterImp formatter, Int32 widthLeft, Boolean emergencyWrap, Boolean breakOnTabs, Double pixelsPerDip)
   at MS.Internal.TextFormatting.SimpleRun.Create(FormatSettings settings, CharacterBufferRange charString, TextRun textRun, Int32 cp, Int32 cpFirst, Int32 runLength, Int32 widthLeft, Int32 idealRunOffsetUnRounded, Double pixelsPerDip)
   at MS.Internal.TextFormatting.SimpleTextLine.Create(FormatSettings settings, Int32 cpFirst, Int32 paragraphWidth, Double pixelsPerDip)
   at MS.Internal.TextFormatting.TextFormatterImp.FormatLineInternal(TextSource textSource, Int32 firstCharIndex, Int32 lineLength, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak, TextRunCache textRunCache)
   at MS.Internal.TextFormatting.TextFormatterImp.FormatLine(TextSource textSource, Int32 firstCharIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak, TextRunCache textRunCache)
   at System.Windows.Controls.TextBlock.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Decorator.MeasureOverride(Size constraint)
   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Window.MeasureOverrideHelper(Size constraint)
   at System.Windows.Window.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

 **Expected behavior:**

I hope the WPF app can behave normally, just like what the Windows Forms apps do.

![image](https://user-images.githubusercontent.com/9959623/104294797-9ac39c00-54fa-11eb-9c28-5a151df10673.png)

Notes: The UWP apps also crashes if the font family is set to the bad one.

 **Minimal repro:**

Here is a minimal reproduction repo: https://github.com/walterlv/Walterlv.Demo.WpfBadFontCrash

The bad font is at the root path of the repo, you can follow the installing and uninstalling instructions to reproduce this issue.

[Download a bad font](https://github.com/walterlv/Walterlv.Demo.WpfBadFontCrash/blob/master/%E4%B8%8D%E7%BB%99%E7%B3%96%E5%B0%B1%E6%8D%A3%E8%9B%8B%E7%9A%84%E4%B8%87%E5%9C%A3%E8%8A%82.TTF?raw=true)

**Comment by lindexi** [comment]
It will also break the UWP application.

**Comment by daisyTian0517** [comment]
1.Please go to `Settings/Personalization/Font`, drag your ttf to the `Add fonts`, after the installation, you can't click it like others. I think there may be some error for your ttf.
2. I tested a Pacifico.ttf download [here ](https://www.fontsquirrel.com/fonts/list/popular), it can be installed successfully, and it can be clicked to preview.Then I went  to `C:\Windows\Fonts`, check the font's Properties, then you can find the custom font's location is different from others. 
3.Here is the steps to use Pacifico: 
     1)Add it to a Folder named Fonts in project.
      2)Add below code to App.xaml
   `  <Application.Resources>
        <FontFamily x:Key="Pacifico">/Font/#Pacifico</FontFamily>
    </Application.Resources>`
      3)To use it in the xaml like below:
   `  <TextBlock Text="ABCDS" FontSize="30" FontFamily="{StaticResource Pacifico}" />`

**Comment by miloush** [comment]
> I think there may be some error for your ttf.

If I understand it correctly the issue is for cases where there is indeed an error in the font, and the expected behaviour is a font fallback rather than an exception.

**Comment by daisyTian0517** [comment]
@miloush When I install his font in `Settings/Personalization/Font`, the setting crashed.
