### ISSUE TITLE
System.ComponentModel.Win32Exception  at MS.Win32.UnsafeNativeMethods.GetWindowText

### ISSUE THREAD

**Issue by DaveSenn** [dotnet/wpf#4181]
* .NET Core Version: .NET 5.0.3
* Windows version: Win10x64 20H2
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Not tested
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? no
 
 **Problem description:**
My WPF application sometimes crashes (see stacktrace below). As you can see from the stacktrace the issue is not caused by my code.
I did some testing and found the application causing my WPF application to crash. In my case NZXT CAM (https://www.nzxt.com/camapp) is responsible for the crashes. The issue can only be reproduced on machines with CAM running.
CAM (a real piss of shit software...but required for controlling the CPU cooler) thinks it has to play task manager and display applications using lots of CPU time. I guess CAM calls `GetWindowText` to get the name of the application to display in it's "task-list".
I know you can't to anything about CAM causing problems...but I think a WPF app should not crash just because another process is trying to read it's window title...? Please consider that not a lot of devs are running this software any may never see this error on their machine...but there are some "real" users there running CAM on their PC...and they don't have a single chance to trace this error back to CAM.
 
 **Actual behavior:** 

System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=A device attached to the system is not functioning.
  Source=WindowsBase
  StackTrace:
   at MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)
   at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at MyApp.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]
 
 **Expected behavior:**
 
Calls to GetWindowText from other processes should not be able to crash a WPF application.

 **Minimal repro:**

I don't know how I should create a minimal repro for this...but if you tell me what additional data you need I will try to provide it to you.

**Comment by SamBent** [comment]
@DaveSenn - 

> I guess CAM calls GetWindowText to get the name of the application to display in it's "task-list"

No, CAM is not calling GetWindowText.  WPF is calling GetWindowText, and CAM is intercepting the call and returning an error result.  WPF cannot distinguish the spurious error from a real error, and so cannot ignore it without also ignoring genuine errors.

The OS implements [GetWindowText ](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowtexta)by sending a [WM_GETTEXT](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-gettext) message to the window, and returning the resulting string.  CAM intercepts this message using [SetWindowHook](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowshookexa), doing nothing to interfere _directly_ with the normal response, but doing something that sets the thread's "last error".  When GetWindowText returns, WPF finds that the return value is 0 (because the window has no title), but that GetLastError returns a non-zero value (because CAM set it _indirectly_, after WPF had carefully set it to 0 before calling GetWindowText).

The moral is that message hooks need to avoid changing the "last error".  CAM is not the only app that gets this wrong, and GetWindowText is not the only Win32 API affected by this kind of bug.

**Comment by jairbubbles** [comment]
Hi @SamBent, I'm seeing the same exception on my side, only two users for now (including me). I don't have any clue on what over application could be doing it wrong.

Wouldn't it make sens to try / catch the native call? I see there is already one in `GetBoundingRectangleCore`.

Otherwise, do you see any workaround on the application side itself? At some point you said :

> When GetWindowText returns, WPF finds that the return value is 0 (because the window has no title),

Does it mean that it only happens when we create a window with no title?

**Comment by SamBent** [comment]
@jairbubbles - Try/catch is probably the right compromise, but I'd want to find all uses of GetWindowText and other methods with the same vulnerability and determine the right place to put the try/catch (perhaps lower down - in UnsafeNativeMethods).

This shouldn't arise on windows that have a title.  That may not help, as you don't have control over all windows (e.g. popups from ComboBox, Menu, ToolTip, etc.).

**Comment by jairbubbles** [comment]
> That may not help, as you don't have control over all windows (e.g. popups from ComboBox, Menu, ToolTip, etc.).

@SamBent Indeed, I think I had once the issue while opening a combo box!

**Comment by jairbubbles** [comment]
Hi @SamBent some progress on that one?

I noticed that we've seen that exception only on .NET5 / .NET Core, we never encountered it on .NET Framework! Now that our app has completely migrated to .NET5 we see this exception occurs more often and it's in fact the crash number 1.

**Comment by jairbubbles** [comment]
Hi @SamBent we're still sctratching our head with that one.

We overrode the `WindowAutomationPeer` for all windows created in our application but we're still getting the crash randomly. As we previously said it's probably due to windows (with no title) create by WPF (combo boxes and so on...) and our fix had no effect on those.

How would you feel to add a try / catch directly here:

https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/WindowAutomationPeer.cs#L48

We would consider the name for the automation peer to be empty if an exception is thrown during the call to `GetWindowText`. It feels reasonable to me 😺

**Comment by deiruch** [comment]
I just ran (again) into the same issue. It occurs on my Microsoft Surface Pro 8, running Windows 11 - no 3rd party executables are running at this point in time, except for the built-in drivers (e.g. from Intel). Thousands of WPF re-layouts reliably trigger the issue on my system.

@SamBent How do you suggest I solve this problem?

**Comment by matthew-a-thomas** [comment]
@DaveSenn @jairbubbles @deiruch Does [my workaround](https://github.com/dotnet/wpf/issues/6026#issuecomment-1051096657) for a very similar (identical?) issue help?

**Comment by jairbubbles** [comment]
Thx @matthew-a-thomas I don't think I've seen an occurence of this issue recently. I'm not sure why though...

**Comment by deiruch** [comment]
Thanks for the tip, @matthew-a-thomas  ! I tried your workaround, to no avail.

The callback is installed correctly, and is even invoked occasionally. However, the callback is not called right before the exception hits.
