### ISSUE TITLE
WPF application crash when typing Chinese quickly in third-party RichEditControl and WPF TextBox

### ISSUE THREAD

**Issue by SamBent** [dotnet/wpf#4984]
**Problem description:**
Typing Chinese can crash (FailFast) due to unexpected re-entrancy from the IME.

[This is a port from a servicing fix in .NET 4.7-4.8.]
 
 **Actual behavior:** 
 Two types of callstacks:
```
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Unrecoverable system error.
Stack:
   at System.Environment.FailFast(System.String)
   at MS.Internal.Invariant.FailFast(System.String, System.String)
   at System.Windows.Documents.TextStore.SetFinalDocumentState(MS.Internal.Documents.UndoManager, System.Collections.Stack, Int32, Int32, Int32, Int32, Int32)
   at System.Windows.Documents.TextStore.HandleCompositionEvents(Int32)
   at System.Windows.Documents.TextStore.GrantLockWorker(LockFlags)
   at System.Windows.Documents.TextStore.RequestLock(LockFlags, Int32 ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
```
```
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Unrecoverable system error.
Stack:
   at System.Environment.FailFast(System.String)
   at MS.Internal.Invariant.FailFast(System.String, System.String)
   at System.Windows.Documents.TextStore.VerifyTextStoreConsistency()
   at System.Windows.Documents.TextStore.GrantLock()
   at System.Windows.Documents.TextStore.GrantLockWorker(LockFlags)
   at System.Windows.Documents.TextStore.RequestLock(LockFlags, Int32 ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
```

**Comment by SamBent** [comment]
Fix ported to 3.1.19, 5.0.10, 6.0.
