### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by wedol** [dotnet/wpf#606]
* .NET Core Version: 3.0.100-preview3-010431
* Windows version: N/A
* Does the bug reproduce also in WPF for .NET Framework 4.8?: N/A

 This is from telemetry and resulted in an app crash. But cannot obtain additional information from client.

<pre>{
  "Exception": {
    "ClassName": "System.NullReferenceException",
    "Message": "Object reference not set to an instance of an object.",
    "Data": {
      "System.Object": null
    },
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Windows.Documents.SplayTreeNode.GetSiblingAtOffset(Int32 offset, Int32& nodeOffset)
   at System.Windows.Documents.TextContainer.GetNodeAndEdgeAtOffset(Int32 offset, Boolean splitNode, SplayTreeNode& node, ElementEdge& edge)
   at System.Windows.Documents.TextPointer..ctor(TextContainer textContainer, Int32 offset, LogicalDirection direction)
   at System.Windows.Documents.TextContainer.CreatePointerAtOffset(Int32 offset, LogicalDirection direction)
   at MS.Internal.PtsHost.TextParaClient.GetTextPositionFromDistance(Int32 dcpLine, Double distance)
   at MS.Internal.Documents.TextParagraphView.GetTextPositionFromPoint(ReadOnlyCollection'1 lines, Point point, Boolean snapToText)
   at MS.Internal.Documents.TextDocumentView.GetTextPositionFromPoint(ParagraphResult paragraph, Point point, Boolean snapToText)
   at MS.Internal.Documents.TextDocumentView.GetTextPositionFromPoint(ReadOnlyCollection'1 paragraphs, ReadOnlyCollection'1 floatingElements, Point point, Boolean snapToText, Boolean snapToTextInFloatingElements)
   at MS.Internal.Documents.TextDocumentView.GetTextPositionFromPoint(ParagraphResult paragraph, Point point, Boolean snapToText)
   at MS.Internal.Documents.TextDocumentView.GetTextPositionFromPoint(ReadOnlyCollection'1 paragraphs, ReadOnlyCollection'1 floatingElements, Point point, Boolean snapToText, Boolean snapToTextInFloatingElements)
   at MS.Internal.Documents.TextDocumentView.GetTextPositionFromPoint(ReadOnlyCollection'1 columns, ReadOnlyCollection'1 floatingElements, Point point, Boolean snapToText)
   at MS.Internal.Documents.TextDocumentView.GetTextPositionFromPoint(Point point, Boolean snapToText)
   at MS.Internal.Documents.TextViewBase.System.Windows.Documents.ITextView.GetTextPositionFromPoint(Point point, Boolean snapToText)
   at MS.Internal.Documents.DocumentPageTextView.GetTextPositionFromPoint(Point point, Boolean snapToText)
   at MS.Internal.Documents.TextViewBase.System.Windows.Documents.ITextView.GetTextPositionFromPoint(Point point, Boolean snapToText)
   at System.Windows.Documents.TextEditorMouse.GetUIElementWhenMouseOver(TextEditor This, Point mouseMovePoint)
   at System.Windows.Documents.TextEditorMouse.UpdateCursor(TextEditor This, Point mouseMovePoint)
   at System.Windows.Documents.TextEditorMouse.OnMouseMoveWithFocus(TextEditor This, MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at StickyNotes.App.Main()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2147467261,
    "Source": "PresentationFramework"    
  },
  "AdditionalData": [
    "IsTerminating: True"
  ]
}</pre>

**Comment by wedol** [comment]
Same exception with additional stack trace from today.

<pre>
{
  "Exception": {
    "ClassName": "MS.Internal.PtsHost.UnsafeNativeMethods.PTS+SecondaryException",
    "Message": null,
    "Data": {
      "System.Object": null
    },
    "InnerException": {
      "ClassName": "System.NullReferenceException",
      "Message": "Object reference not set to an instance of an object.",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at System.Windows.Documents.SplayTreeNode.GetSiblingAtOffset(Int32 offset, Int32& nodeOffset)
   at System.Windows.Documents.TextContainer.GetNodeAndEdgeAtOffset(Int32 offset, Boolean splitNode, SplayTreeNode& node, ElementEdge& edge)
   at System.Windows.Documents.TextContainer.CreateStaticPointerAtOffset(Int32 offset)
   at MS.Internal.PtsHost.Line.GetTextRun(Int32 dcp)
   at MS.Internal.PtsHost.TextFormatterHost.GetTextRun(Int32 textSourceCharacterIndex)
   at MS.Internal.TextFormatting.TextRunCacheImp.FetchTextRun(FormatSettings settings, Int32 cpFetch, Int32 cpFirst, Int32& offsetToFirstCp, Int32& runLength)
   at MS.Internal.TextFormatting.FormatSettings.FetchTextRun(Int32 cpFetch, Int32 cpFirst, TextRun& textRun, Int32& runLength)
   at MS.Internal.TextFormatting.SimpleTextLine.Create(FormatSettings settings, Int32 cpFirst, Int32 paragraphWidth, Double pixelsPerDip)
   at MS.Internal.TextFormatting.TextFormatterImp.FormatLineInternal(TextSource textSource, Int32 firstCharIndex, Int32 lineLength, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak, TextRunCache textRunCache)
   at MS.Internal.TextFormatting.TextFormatterImp.FormatLine(TextSource textSource, Int32 firstCharIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak, TextRunCache textRunCache)
   at MS.Internal.PtsHost.Line.Format(FormattingContext ctx, Int32 dcp, Int32 width, Int32 trackWidth, TextParagraphProperties lineProps, TextLineBreak textLineBreak)
   at MS.Internal.PtsHost.TextParagraph.FormatLineCore(Line line, IntPtr pbrLineIn, FormattingContext ctx, Int32 dcp, Int32 width, Int32 trackWidth, Boolean firstLine, Int32 dcpLine)
   at MS.Internal.PtsHost.TextParagraph.FormatLine(TextParaClient paraClient, Int32 iArea, Int32 dcp, IntPtr pbrlineIn, UInt32 fswdir, Int32 urStartLine, Int32 durLine, Int32 urStartTrack, Int32 durTrack, Int32 urPageLeftMargin, Boolean fAllowHyphenation, Boolean fClearOnLeft, Boolean fClearOnRight, Boolean fTreatAsFirstInPara, Boolean fTreatAsLastInPara, Boolean fSuppressTopSpace, IntPtr& lineHandle, Int32& dcpLine, IntPtr& ppbrlineOut, Int32& fForcedBroken, FSFLRES& fsflres, Int32& dvrAscent, Int32& dvrDescent, Int32& urBBox, Int32& durBBox, Int32& dcpDepend, Int32& fReformatNeighborsAsLastLine)
   at MS.Internal.PtsHost.PtsHost.FormatLine(IntPtr pfsclient, IntPtr pfsparaclient, IntPtr nmp, Int32 iArea, Int32 dcp, IntPtr pbrlineIn, UInt32 fswdir, Int32 urStartLine, Int32 durLine, Int32 urStartTrack, Int32 durTrack, Int32 urPageLeftMargin, Int32 fAllowHyphenation, Int32 fClearOnLeft, Int32 fClearOnRight, Int32 fTreatAsFirstInPara, Int32 fTreatAsLastInPara, Int32 fSuppressTopSpace, IntPtr& pfsline, Int32& dcpLine, IntPtr& ppbrlineOut, Int32& fForcedBroken, FSFLRES& fsflres, Int32& dvrAscent, Int32& dvrDescent, Int32& urBBox, Int32& durBBox, Int32& dcpDepend, Int32& fReformatNeighborsAsLastLine)",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": null,
      "HResult": -2147467261,
      "Source": "PresentationFramework",
      "WatsonBuckets": null
    },
    "HelpURL": null,
    "StackTraceString": "   at MS.Internal.PtsHost.UnsafeNativeMethods.PTS.ErrorTrace(Int32 fserr, PtsContext ptsContext)
   at MS.Internal.PtsHost.PtsPage.UpdateBottomlessPage()
   at MS.Internal.PtsHost.FlowDocumentPage.FormatBottomless(Size pageSize, Thickness pageMargin)
   at MS.Internal.Documents.FlowDocumentFormatter.Format(Size constraint)
   at MS.Internal.Documents.FlowDocumentView.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at StickyNotes.App.Main()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146233088,
    "Source": "PresentationFramework",
    "WatsonBuckets": null
  },
  "AdditionalData": [
    "IsTerminating: True"
  ]
}
</pre>

**Comment by rladuca** [comment]
I haven't found anything to indicate that this is a Watson hitter in 4.8.  I am going to move this to the bucket for additional Watson data.

@grubioe Please ensure this goes under the Watson Epic.

**Comment by wedol** [comment]
What is status on this issue? My users still crashing on this issue. (cca 600 users per day with ~5 crashes per day on this issue)

**Comment by vatsan-madhavan** [comment]
What’s the name of the exe? Is there a characteristic version associated with the exe corresponding to 3.0 GA ?
