### ISSUE TITLE
DivideByZeroException in VirtualizingStackPanel after WM_STYLECHANGED

### ISSUE THREAD

**Issue by milos12345** [dotnet/wpf#6225]
* .NET 4.8
* Windows version: 10.0.22000.0 and 10.0.19043.0 and all other
 
 **Problem description:**
I am capturing WM messages in a rolling buffer and on program crash I get see these preceding most crashes
```
WM_STYLECHANGING
WM_STYLECHANGED
WM_STYLECHANGING
WM_STYLECHANGED
```
The program crashes with
```
System.DivideByZeroException: Attempted to divide by zero.
   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(Size constraint, Nullable`1& lastPageSafeOffset, List`1& previouslyMeasuredOffsets, Nullable`1& lastPagePixelSize, Boolean remeasure)
   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
  at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ItemsPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ScrollContentPresenter.MeasureOverride(Size constraint)
```
- Crashes 1/100 runs
- No my code in stack trace
- I tried to set MinWidth/MinHeight in everything that goes in any scrollviewer, but I still get these crashes
Are the window messages related and how would they cause this (or just they cause the remeasurement)?
How would I go about finding the culprit/workaround?

**Comment by lindexi** [comment]
@milos12345 What is the minimal repro?

**Comment by lindexi** [comment]
@milos12345 May be fixed in https://github.com/dotnet/wpf/pull/6015

**Comment by lindexi** [comment]
6.0.3 has been released today, please consider updating.

**Comment by milos12345** [comment]
I cannot reproduce it myself and only get these crashes through Application Insights and it is less than 1 in 100 users/runs. If there was a way to have names of VirtualizingStackPanel in Stack Trace I could at least know which one (out of 10+) is causing the issue and what might be displayed in it. I'll see what happens when I try .NET6 but it is a large and complex software ("One Commander") so it might be easier just getting adapt VirtualizingStackPanel.cs from that build

**Comment by gurpreet-wpf** [comment]
@milos12345 Please create a new issue with minimal repro attached. Thanks
