### ISSUE TITLE
BindingExpressionBase.ValidateWithoutUpdate does never validate

### ISSUE THREAD

**Issue by trivalik** [dotnet/wpf#6244]
* .NET Core Version: 6.0
* Windows version: 21H2
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 
 
 **Problem description:**
Adding a ValidationRule in code behind (because it rely on a value which is not known on startup) does not update validation the intuition way. Try to get arround this and call `ValidationWithoutUpdate` does nothing.
 
 **Actual behavior:** 
You have to call UpdateSource() before ValidateWithoutUpdate()
 **Expected behavior:**
 ValidateWithoutUpdate() would update validation without require of UpdateSource()
 **Minimal repro:**

```
    public partial class MainWindow : Window
    {
        public class NameRule : ValidationRule
        {
            public int AdditionalInformationWhichWouldRequireBinding { get; set; }
            public override ValidationResult Validate(object value, CultureInfo cultureInfo)
            {
                int age = 0;
                try
                {
                    if (((string)value).Length > 0)
                        age = int.Parse((String)value);
                }
                catch (Exception e)
                {
                    return new ValidationResult(false, $"Illegal characters or {e.Message}");
                }

                if(AdditionalInformationWhichWouldRequireBinding < age)
                    return new ValidationResult(false, $"Illegal Range");

                return ValidationResult.ValidResult;
            }
        }

        NameRule _nameRule;

        public MainWindow()
        {
            InitializeComponent();

            var binding = BindingOperations.GetBinding(txtNewName, TextBox.TextProperty);
            var bindingex = BindingOperations.GetBindingExpression(txtNewName, TextBox.TextProperty);
            var role = new NameRule();
            binding.ValidationRules.Add(role);
            _nameRule = role;
            DataContextChanged += MainWindow_DataContextChanged;
            DataContext = new NewViewModel
            {
                NewName = "abc"
            };
        }

        private void MainWindow_DataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            _nameRule.AdditionalInformationWhichWouldRequireBinding = ((NewViewModel)DataContext).RequiredForValidation;
            var binding = BindingOperations.GetBindingExpression(txtNewName, TextBox.TextProperty);

            binding.UpdateSource();
            binding.ValidateWithoutUpdate();
        }
    }

    class NewViewModel : INotifyPropertyChanged
    {
        private string newName;

        public string NewName { get => newName;
            set {
                newName = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(NewName)));
            }
        }

        public int RequiredForValidation { get; set; }

        public event PropertyChangedEventHandler? PropertyChanged;
    }
}
```

XAML:
```
<TextBox x:Name="txtNewName" Text="{Binding NewName}"/>
```

Additional:
- The first value which is validated in above example is `string.Empty` not `"abc"`.
- if ValidationResult.ValidResult is returned `ValidateWithoutUpdate` throws NullReferenceException
```
   at System.Windows.Data.BindingExpression.ConvertProposedValue(Object value)
   at System.Windows.Data.BindingExpression.ValidateAndConvertProposedValue(Collection`1& values)
   at System.Windows.Data.BindingExpressionBase.ValidateWithoutUpdate()
   at WpfNet6Test.MainWindow.MainWindow_DataContextChanged(Object sender, DependencyPropertyChangedEventArgs e)
```
- Solution would be to wait until Expression is activated and delay force valdiation with:
```
Dispatcher.BeginInvoke(DispatcherPriority.Normal, new Action(ForceValidation));

        private void ForceValidation()
        {
            var binding = BindingOperations.GetBindingExpression(txtNewName, TextBox.TextProperty);
            binding.UpdateSource();
        }
```
but `ValidateWithoutUpdate` is still without function.

**Comment by anjali-wpf** [comment]
@trivalik 
Looking at some of the validation code with ILSpy it has some checks in the background that determine if validation is required or not.

In your attached property changed handler, after

`binding.ValidationRules.Add(role);`

add

```
BindingOperations.ClearBinding(d, prop);
BindingOperations.SetBinding(d, prop, binding);
```

This must somehow set the internal 'validation required' flag which forces it to validate.

Also you'll probably want to check that `GetBindingExpression` doesn't return null, this will run any converters you have attached (presumably to supply the converted value to converters with `ValidationStep` set to ConvertedProposedValue), but will not update the source. And, of course, you'll have to call this in some event, perhaps TextChanged or somesuch. Here is the MSDN documentation for it: https://msdn.microsoft.com/en-us/library/system.windows.data.bindingexpressionbase.validatewithoutupdate(v=vs.110).aspx


Use this code:

```
    BindingExpression bindingex = 
    txtNewName.GetBindingExpression(TextBox.TextProperty);
    bindingex.ValidateWithoutUpdate();
```

If you want to update it's source after check, use this code:

  ```
  BindingExpression bindingex = 
    txtNewName.GetBindingExpression(TextBox.TextProperty);
    bindingex.ValidateWithoutUpdate();
    if (bindingex!=null && !bindingex.HasError)
    bindingex.UpdateSource();
```

**Comment by trivalik** [comment]
Thanks for your effort. In case there is no bugfix in WPF we can close this issue. I keep your suggestion in mind if I get into this again.
