### ISSUE TITLE
WPF 3D App crashes without exception on Intel UHD770

### ISSUE THREAD

**Issue by ToxicToxine** [dotnet/wpf#6312]
* .NET Core Version: 6
* Windows version: 21H2 (Build 22000.556)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 
 
 **Problem description:**
I created a simple Testapplication using WPF 3D Media. It only Contains a Viewport3D and a simple MeshGeometry.
Evertime i execute this on my Machine (Intel I9-12900K and Intel UHD770) the program crashes without any Exception or error in the Output. 
 
 **Actual behavior:** 
 Only Crashes, no Exceptions etc.
 **Expected behavior:**
 Rendering of Window with Geometry
 **Minimal repro:**
[Win11TestApp3d.zip](https://github.com/dotnet/wpf/files/8350682/Win11TestApp3d.zip)

**Comment by lindexi** [comment]
@ToxicToxine Could you use [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump?WT.mc_id=WD-MVP-5003260) tool to collect the dump file of your process when it crashes

**Comment by AsgardXIV** [comment]
Also encountering the same issue (or similar issue).

I reported to Intel and have a support ticket open with them, but not making a lot of progress. [Intel Community Link](https://community.intel.com/t5/Graphics/Crash-with-UHD-770-in-WPF-applications-using-Viewport3D/m-p/1370393#M106529).

The most I can see is:

```
UCEERR_RENDERTHREADFAILURE (0x88980406)
System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (0x88980406)
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

If I run ProcDump, I don't actually get a dump, just get
```
[13:53:58] Exception: E06D7363.?AV_com_error@@
[13:54:08] Exception: E0434352.CLR
[13:54:08] Exception: E0434352.CLR
[13:54:08] Exception: E0434352.CLR
[13:54:08] Exception: E0434352.CLR
[13:54:08] Exception: C00000FD.STACK_OVERFLOW
[13:54:08] The process has exited.
[13:54:08] Dump count not reached.
```

**Comment by lindexi** [comment]
@AsgardXIV Could you see https://github.com/dotnet/wpf/issues/3817 ?

**Comment by AsgardXIV** [comment]
I'm currently running 30.0.101.1631 (latest for 12th gen as of today) and the issue does occur there.
I did try with previous versions last week, and as far as I have been able to test, there is no driver where this works on 12th gen.

**Comment by AsgardXIV** [comment]
The behavior has changed for me with either a Windows Update, DotNet Update or an Intel Driver update. Not sure exactly when it changed, and all 3 had updates.

It no longer crashes but the rendering is corrupt/incorrect when connected to a monitor on the Intel graphics.

In the attached videos:
Video 1: Launched on the Intel connected monitor, immediately corrupt.
Video 2: Launched on the NVidia connected monitor and it's correct, the moment it touches the intel connect monitor it corrupts.

[Video 1](https://user-images.githubusercontent.com/95163444/161824640-e93804c4-a57d-4ab3-b3a7-190c1bb9661a.MOV)
[Video 2](https://user-images.githubusercontent.com/95163444/161824678-7681ec06-d8b5-4117-8c4e-7d7f5a8fc29d.MOV)

**Versions**
Intel Driver: 30.0.101.1660
Windows 11: Version 10.0.22000 Build 22000
DotNet: 5.0.15
NVidia Driver: 30.0.15.1215

**Comment by ToxicToxine** [comment]
@AsgardXIV  we, in the comapany i work for, have exactly the same result.
The new part is this Exception thrown, when changing Monitors.

![2022-04-12 07_32_03-AnalyserCentral (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/102365476/162887530-4cab4475-8d1b-49ec-8259-94f7ed8db97d.png)
n

**Comment by AsgardXIV** [comment]
I got a response from Intel to say they reproduced the issue and they it's fixed in an internal driver build. No timeline on a release yet.
