### ISSUE TITLE
WeakEventManager lock issue

### ISSUE THREAD

**Issue by zgabi** [dotnet/wpf#6452]
.NET 6.0.202
Windows Server 2022 21H2 20348.643
Does the bug reproduce also in WPF for .NET Framework 4.8?: yes

 **Problem description:**
Collection was modified exception in `WeakEventTable `cleanup.
It seems that the problem occures only when `EnableWeakEventMemoryImprovements` is true. 

_dataTable is changed in the PurgeInternal code in this loop:
https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/WeakEventTable.cs#L336-L348

Somewhere here:
https://github.com/dotnet/wpf/blob/bdfe29afcaa879c55aa3ed6541698cdc42be4dd8/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/WeakEventManager.cs#L406-L445

 **Actual behavior:** 
I receive the following exception sometimes which terminates the whole process (of course I could catch it in the `Dispatcher.UnhandledException` event handler):

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Hashtable.HashtableEnumerator.MoveNext()
   at MS.Internal.WeakEventTable.Purge(Boolean purgeAll)
   at MS.Internal.CleanupHelper.DoCleanup(Boolean forceCleanup)
   at MS.Internal.CleanupHelper.OnCleanupTick(Object sender, EventArgs e)
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
 
 **Expected behavior:**
No unhandled exception
 
 **Minimal repro:**
Open the attached project, execute it and press the button several times.
[WeakEventManagerTest.zip](https://github.com/dotnet/wpf/files/8506598/WeakEventManagerTest.zip)

**Comment by lindexi** [comment]
It seems to be a bug

**Comment by Camios** [comment]
Also reproducible on .NET 8 and .NET 10

**Comment by kmaddock** [comment]
The problem is in WeakEventManager.Purge:
```
                if (ListenerList.PrepareForWriting(ref list) && source != null)
                {
                    Table[this, source] = list;
                }
```

If the EnableWeakEventMemoryImprovements config flag is true, then WeakEventTable.Purge enumerates through _dataTable instead of taking a copy, so if ListenerList.PrepareForWriting returns true (due to concurrent readers) then writing to Table[this, source] will invalidate the enumeration, causing the exception
