### ISSUE TITLE
WPF touch function does not work.

### ISSUE THREAD

**Issue by HouZack** [dotnet/wpf#7069]
* .NET Core Version: ALL
* Windows version: Windows 10 Version 21H2
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 
 
 **Problem description:**
Sometimes, I met a problem that wpf touch function does not work. I have no idea what's wrong with my computer. 
I make a screen recording about this bug .
 **Actual behavior:** 
 I summarize some tests:
1. All of the wpf touch function is abnormal even if I restart wpf application. (Button click with touch, inkcanvas touch...).
2. Disable HID-compliant touch screen, then enable it,  still does not work.
3. Change touch device(monitor) and restart application still does not work.
4. Change another account(B user) and don't sign out (A current user) Windows, B user's wpf touch is normal,
   and switch to (A user) that wpf touch still don't work.
5. We doubt there are something wrong with Wisp, because I use other app that is not wpf app, it use wisp and also have the similar question.
6. If I use "EnablePointerSupport", touch will be normal. But there are some reason I cannot use "EnablePointerSupport". I write a easy sample code to reproduce as attach video.
 **Expected behavior:**
 Touch can work well.
 **Minimal repro:**
When this error occurs, it can always be reproduced as long as Windows is not restarted.

https://user-images.githubusercontent.com/113828370/190896784-37151d1a-f6f1-4448-beeb-59d9798ac2bd.mp4

**Comment by lindexi** [comment]
@HouZack What is your DPI ? Could you change the system DPI to 100%

**Comment by HouZack** [comment]
> @HouZack What is your DPI ? Could you change the system DPI to 100%

**Comment by HouZack** [comment]
> @HouZack What is your DPI ? Could you change the system DPI to 100%

My DPI is always 100%.

**Comment by lindexi** [comment]
@HouZack Have you two touch screen?

**Comment by HouZack** [comment]
> @HouZack Do you have two touch screen?

Yes, even if I use the second touch screen, the touch still  doesn't work.

**Comment by lindexi** [comment]
@HouZack The bad news is maybe it is a known issue. See https://github.com/dotnet/wpf/issues/2054

Could you add `new WindowInteropHelper(this).EnsureHandle();` before you show the window to test? Thank you

**Comment by HouZack** [comment]
> 

Because I have rebooted computer and need to wait for next time the problem occurs.

**Comment by HouZack** [comment]
> @HouZack The bad news is maybe it is a known issue. See #2054
> 
> Could you add `new WindowInteropHelper(this).EnsureHandle();` before you show the window to test? Thank you
Because I have rebooted computer and need to wait for next time the problem occurs.

**Comment by HouZack** [comment]
> @HouZack The bad news is maybe it is a known issue. See #2054
> 
> Could you add `new WindowInteropHelper(this).EnsureHandle();` before you show the window to test? Thank you

@lindexi I add `new WindowInteropHelper(this).EnsureHandle();` but touch still not work. Thanks.
![image](https://user-images.githubusercontent.com/113828370/197093106-e9e3bf77-7472-4054-b59f-e2a827f7461d.png)

**Comment by lindexi** [comment]
@HouZack Is your Application TopMost ?

**Comment by HouZack** [comment]
> @HouZack Is your Application TopMost ?
> 
> See https://developercommunity.visualstudio.com/content/problem/255063/on-windows-10-1803-all-applications-lost-touch-or.html

No, I don't set TopMost. And I try to set it to true or false, touch still not work.

**Comment by lindexi** [comment]
@HouZack  And I created the tool application which can help us to collect the touch info, see https://github.com/dotnet-campus/ManipulationDemo

**Comment by HouZack** [comment]
> @HouZack Could you try re-start the touch module by the code:
> 
> ```cs
>             var windowInteropHelper = new WindowInteropHelper(this);
>             var hwndSource = HwndSource.FromHwnd(windowInteropHelper.Handle);
> 
>             object stylusLogic = GetStylusLogic();
> 
>             if (stylusLogic == null)
>             {
>                 return;
>             }
> 
>             Type inputManagerType = typeof(System.Windows.Input.InputManager);
>             var wispLogicType = inputManagerType.Assembly.GetType("System.Windows.Input.StylusWisp.WispLogic");
> 
>             var windowInteropHelper = new WindowInteropHelper(this);
>             var hwndSource = HwndSource.FromHwnd(windowInteropHelper.Handle);
> 
>             var unRegisterHwndForInputMethodInfo = wispLogicType.GetMethod("UnRegisterHwndForInput",
>                 BindingFlags.Instance | BindingFlags.NonPublic);
> 
>             unRegisterHwndForInputMethodInfo.Invoke(stylusLogic, new object[] {hwndSource});
> 
> 
>             var registerHwndForInputMethodInfo = wispLogicType.GetMethod("RegisterHwndForInput",
>                 BindingFlags.Instance | BindingFlags.NonPublic);
> 
>             registerHwndForInputMethodInfo.Invoke(stylusLogic, new object[]
>             {
>                 InputManager.Current,
>                 PresentationSource.FromVisual(this)
>             });
> 
>         private object GetStylusLogic()
>         {
>             TabletDeviceCollection devices = System.Windows.Input.Tablet.TabletDevices;
> 
>             if (devices.Count > 0)
>             {
>                 // Get the Type of InputManager.
>                 Type inputManagerType = typeof(System.Windows.Input.InputManager);
> 
>                 // Call the StylusLogic method on the InputManager.Current instance.
>                 object stylusLogic = inputManagerType.InvokeMember("StylusLogic",
>                     BindingFlags.GetProperty | BindingFlags.Instance | BindingFlags.NonPublic,
>                     null, InputManager.Current, null);
> 
>                 return stylusLogic;
>             }
> 
>             return null;
>         }
> ```
> 
> Or running my demo: https://github.com/lindexi/lindexi_gd/tree/bdf0e7a0/LeekailawnahelNarjailearyaydi

@lindexi It will crash in "HwndSource.FromHwnd(windowInteropHelper.Handle)"
![image](https://user-images.githubusercontent.com/113828370/197096746-b99fa366-7ccb-4ddb-b5ac-2e4660677aac.png)

**Comment by HouZack** [comment]
> @HouZack And I created the tool application which can help us to collect the touch info, see https://github.com/dotnet-campus/ManipulationDemo
@lindexi these are my application messages and logs.
![image](https://user-images.githubusercontent.com/113828370/197097803-5813cf1c-0ae6-41c6-a7d0-787afea85a8e.png)

[log.txt](https://github.com/dotnet/wpf/files/9835227/log.txt)

**Comment by HouZack** [comment]
@lindexi I followed you blog and try to restart touch, it still not work.
https://blog.lindexi.com/post/WPF-%E8%A7%A6%E6%91%B8%E5%A4%B1%E6%95%88-%E8%AF%95%E8%AF%95%E9%87%8D%E5%90%AF%E8%A7%A6%E6%91%B8.html
![image](https://user-images.githubusercontent.com/113828370/197098681-af6369b6-424a-4257-a89b-2c604247a7ba.png)

**Comment by lindexi** [comment]
@HouZack  I know the reason for this. Because the touch module of the system throws a COM exception.

**Comment by HouZack** [comment]
> @HouZack I know the reason for this. Because the touch module of the system throws a COM exception.

@lindexi Is reboot PC the only solution currently?

**Comment by lindexi** [comment]
@HouZack WPF will use [RealTimeStylus](https://learn.microsoft.com/en-us/windows/win32/tablet/realtimestylus-reference) to get the touch by default. But WPF init the [RealTimeStylus](https://learn.microsoft.com/en-us/windows/win32/tablet/realtimestylus-reference) fail and throw the COM exception.

**Comment by lindexi** [comment]
@HouZack I'm guessing the possible reasons are:

- There is a problem with the touch module of the system
 - Such as the devices
-  Apps are injected with malware
 - You can try to get the module injected by the application by VMMap tool or ProcessExplorer tool

More test methods:

- Using WM_Pointer: 

```csharp
        public App()
        {
            AppContext.SetSwitch("Switch.System.Windows.Input.Stylus.EnablePointerSupport", true);
        }
```

**Comment by kircsa08** [comment]
@HouZack 
Is there any solution? I am facing with the same issue..

**Comment by lindexi** [comment]
@kircsa08 You can try the two ways to solve it when you and  @HouZack issues are the same.

1. re-start the touch module: https://github.com/dotnet/wpf/issues/7069#issuecomment-1286364219
2. Enable the Pointer: https://github.com/dotnet/wpf/issues/7069#issuecomment-1286429945

**Comment by kircsa08** [comment]
> @kircsa08 You can try the two ways to solve it when you and  @HouZack issues are the same.
> 
> 
> 
> 1. re-start the touch module: https://github.com/dotnet/wpf/issues/7069#issuecomment-1286364219
> 
> 2. Enable the Pointer: https://github.com/dotnet/wpf/issues/7069#issuecomment-1286429945

thank you so much, the 2nd workaround has solved my issue !!

**Comment by lindexi** [comment]
@RVPryimak Could you add more exception info?

**Comment by RVPryimak** [comment]
@lindexi Actualy that is all what i receive. Also i find out that MoudleDoubleClick command stop work with touch after i run 'AppContext.SetSwitch("Switch.System.Windows.Input.Stylus.EnablePointerSupport", true);'

**Comment by RVPryimak** [comment]
@lindexi In my case touch stop working well after any dialog is closed. After this Main windows stop react on touch event at least for first 10. Event if I subscribe to TouchDown event its not raise for first 10-15 click

**Comment by lindexi** [comment]
@RVPryimak Your problems are beyond imagination

**Comment by RVPryimak** [comment]
@lindexi I will try to provide small example with my issue. I will be appreciate if you will have time to look on it

**Comment by wangtenghong** [comment]
@lindexi 
I already using the fix suggestion that you mentioned in this post
```
public App()
        {
            AppContext.SetSwitch("Switch.System.Windows.Input.Stylus.EnablePointerSupport", true);
        }
```

But our co-work company using a new touch panel in ongoing project and using our product for verification but found our software won't react to click/touch/stylus moving.  The error message as following and in attachments.  I am wondering if you could do help to check them and give some clues to fix this problem.
> 10-30-2023 00:56:23 [Exception in LogUnhandledException] exception: System.ArgumentException: '{0}' must be greater than or equal to '{1}'. (Parameter 'maximum')
>    at System.Windows.Input.StylusPointPropertyInfo..ctor(StylusPointProperty stylusPointProperty, Int32 minimum, Int32 maximum, StylusPointPropertyUnit unit, Single resolution)
>    at System.Windows.Input.StylusPointer.PointerStylusPointPropertyInfoHelper.CreatePropertyInfo(POINTER_DEVICE_PROPERTY prop)
>    at System.Windows.Input.StylusPointer.PointerTabletDeviceInfo.TryInitializeSupportedStylusPointProperties()
>    at System.Windows.Input.StylusPointer.PointerTabletDeviceInfo.TryInitialize()
>    at System.Windows.Input.StylusPointer.PointerTabletDeviceCollection.Refresh()

![HID_01](https://github.com/dotnet/wpf/assets/13567358/49e5dbdf-9035-49d3-be44-dfbff6ed5430)
![HID_02](https://github.com/dotnet/wpf/assets/13567358/b7a5ec35-1794-4d19-84f3-f1d7bb332f1a)
![HID_03](https://github.com/dotnet/wpf/assets/13567358/ecb643cb-4484-44fe-bf78-04a0e1a26ef9)
[part-of-log.txt](https://github.com/dotnet/wpf/files/13331378/part-of-log.txt)

**Comment by lindexi** [comment]
@wangtenghong The exception as follow says the touch data do not match the HID Descriptors define.

```
10-30-2023 00:56:23 [Exception in LogUnhandledException] exception: System.ArgumentException: '{0}' must be greater than or equal to '{1}'. (Parameter 'maximum')
at System.Windows.Input.StylusPointPropertyInfo..ctor(StylusPointProperty stylusPointProperty, Int32 minimum, Int32 maximum, StylusPointPropertyUnit unit, Single resolution)
```

Common issues often involve defining the width and height of touch points in the HID descriptor, but the actual reported touch point data only includes X and Y coordinates, without the width and height information. You can use the BusHound tool to capture packets to understand the touch point data reported by your touch device, and check if there are any definition errors. Additionally, it's also possible that the points you output exceed the maximum and minimum value range defined by your descriptor.

**Comment by lindexi** [comment]
And from the code of the constructor in StylusPointPropertyInfo, it is evident that there is an error in your data. Your maximum value is less than your minimum value.

https://github.com/dotnet/wpf/blob/c8a6d45e15701297c5c4bb5714d6c76350c6e956/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/StylusPointPropertyInfo.cs#L64-L67
