### ISSUE TITLE
InvalidOperationException from valid PathFigure definition

### ISSUE THREAD

**Issue by LyndonGingerich** [dotnet/wpf#7110]
* .NET Core Version: 6.0.9
* Windows version: 10.0.19044 Build 19044
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/main/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**

The program throws an exception rather than running.

 **Actual behavior:** 
 
```
System.Windows.Markup.XamlParseException: 'Set property 'System.Windows.Shapes.Path.Data' threw an exception.' Line number '14' and line position '19'. ---> System.InvalidOperationException: Current local value enumeration is outdated because one or more local values have been set since its creation.
   at System.Windows.DependencyObject.InsertEntry(EffectiveValueEntry entry, UInt32 entryIndex)
   at System.Windows.DependencyObject.SetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, Int32 targetIndex, PropertyMetadata metadata, Object value, BaseValueSourceInternal valueSource)
   at System.Windows.UncommonField`1.SetValue(DependencyObject instance, T value)
   at System.Windows.DependencyObject.UpdateSourceDependentLists(DependencyObject d, DependencyProperty dp, DependencySource[] sources, Expression expr, Boolean add)
   at System.Windows.DependencyObject.ChangeExpressionSources(Expression expr, DependencyObject d, DependencyProperty dp, DependencySource[] newSources)
   at System.Windows.Data.BindingExpressionBase.ChangeSources(WeakDependencySource[] newSources)
   at MS.Internal.Data.ClrBindingWorker.ReplaceDependencySources()
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.AttachDataItem()
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.OnInheritanceContextChanged(Object sender, EventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Windows.DependencyObject.OnInheritanceContextChanged(EventArgs args)
   at System.Windows.Media.PathSegmentCollection.OnInheritanceContextChangedCore(EventArgs args)
   at System.Windows.DependencyObject.OnInheritanceContextChanged(EventArgs args)
   at System.Windows.Media.PathFigureCollection.OnInheritanceContextChangedCore(EventArgs args)
   at System.Windows.DependencyObject.OnInheritanceContextChanged(EventArgs args)
   at System.Windows.Freezable.AddInheritanceContext(DependencyObject context, DependencyProperty property)
   at System.Windows.DependencyObject.ProvideSelfAsInheritanceContext(DependencyObject doValue, DependencyProperty dp)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at PathFigureRepro.MainWindow.InitializeComponent() in C:\Users\Lyndon.G\Desktop\PathFigureRepro\PathFigureRepro\MainWindow.xaml:line 1
   at PathFigureRepro.MainWindow..ctor() in C:\Users\Lyndon.G\Desktop\PathFigureRepro\PathFigureRepro\MainWindow.xaml.cs:line 25
```

 **Expected behavior:**
 
Program runs

 **Minimal repro:**

```XAML
<Path Stroke="HotPink" StrokeThickness="1">
    <Path.Data>
        <PathGeometry>
            <PathFigure x:Name="StartFigure">
                <LineSegment Point="{Binding StartPoint, ElementName=StartFigure}" />
            </PathFigure>
        </PathGeometry>
    </Path.Data>
</Path>
```

[PathFigureRepro.zip](https://github.com/dotnet/wpf/files/9636938/PathFigureRepro.zip)

(Stolen from [MSDN Forums](https://social.msdn.microsoft.com/forums/vstudio/en-US/9c4ba357-6341-4a58-b76d-3858f3717c0d/error-binding-pathdata-in-35-sp1?forum=wpf) after experiencing a similar exception)

**Comment by lindexi** [comment]
![](https://user-images.githubusercontent.com/16054566/192266483-008029bf-bc37-4789-8608-2ec2fa0a045d.png)

It looks like this behavior is as expected from the code

**Comment by LyndonGingerich** [comment]
> It looks like this behavior is as expected from the code

The exception is in the code, yes, but should this simple XAML be triggering the conditions to throw it? Is this the behavior intended by the designers?

**Comment by LyndonGingerich** [comment]
This code throws the same exception:
```xaml
<Path Stroke="HotPink" StrokeThickness="1">
    <Path.Data>
        <PathGeometry>
            <PathFigure x:Name="StartFigure">
                <LineSegment IsStroked="{Binding ElementName=StartFigure, Path=IsFilled}" />
            </PathFigure>
        </PathGeometry>
    </Path.Data>
</Path>
```

**Comment by LyndonGingerich** [comment]
Here's an MRE from the `Behavior` I was writing when I encountered this exception.

[PathFigureRepro.zip](https://github.com/dotnet/wpf/files/9649647/PathFigureRepro.zip)

**Comment by miloush** [comment]
Note that this is a parser exception, setting it up in codebehind does not throw.

@LyndonGingerich out of curiosity, what are you trying to achieve in terms of the geometry behavior?

**Comment by LyndonGingerich** [comment]
> @LyndonGingerich out of curiosity, what are you trying to achieve in terms of the geometry behavior?

I want to set up a `Behavior` with a `StartX` property that sets `PathFigure.StartPoint` to `new Point(StartX, 0.0)`.

**Comment by miloush** [comment]
I can see that from the code, but why? The repro project does not do anything even if it succeeded, it would be good to have something to actually see that the binding is working.

**Comment by LyndonGingerich** [comment]
> I can see that from the code, but why?

> (Stolen from MSDN Forums after experiencing a similar exception)

I have not posted my behavior code. It seemed to me unnecessarily complex for the issue.

> The repro project does not do anything even if it succeeded, it would be good to have something to actually see that the binding is working.

Here is a reproduction with a visual.

[PathFigureRepro2.zip](https://github.com/dotnet/wpf/files/9778517/PathFigureRepro2.zip)

**Comment by miloush** [comment]
Thank you, that confirms it is working at runtime. (just in case, `PathFigure` has `IsClosed` for this purpose)

Marco already confirmed this is a bug on the forums, given the year I am guessing not the easiest one to fix :)

**Comment by LyndonGingerich** [comment]
> (just in case, PathFigure has IsClosed for this purpose)

True. This is a mere MRE. If you want a more convincing use case, I'll post my `Behavior` code.

> I am guessing not the easiest one to fix :)

Bummer.
