### ISSUE TITLE
Exception "Collection was modified" in System.Windows.Input.StylusWisp on remote desktop

### ISSUE THREAD

**Issue by Lumoryel** [dotnet/wpf#7222]
Hi there,
got this exception today on a remote machine directly after connecting via windows remote desktop:

> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
>    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>    at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
>    at System.Windows.Input.StylusWisp.WispLogic.OnTabletAdded(UInt32 wisptisIndex)
>    at System.Windows.Input.StylusWisp.WispLogic.HandleMessage(WindowMessage msg, IntPtr wParam, IntPtr lParam)
>    at System.Windows.SystemResources.InvalidateTabletDevices(WindowMessage msg, IntPtr wParam, IntPtr lParam)
>    at System.Windows.SystemResources.SystemThemeFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

We have a .NET Framework 4.8 WPF Program running in the background, the window was not visible at that moment.
Running on Windows 11 Pro.

**Comment by dipeshmsft** [comment]
Can you provide us a sample repro application ?

**Comment by Lumoryel** [comment]
Unfortunately not, it happened just one time when I connected via remote desktop.
Could it be a (threading?)-Problem in WispLogic.OnTabletAdded ?

**Comment by lindexi** [comment]
@Lumoryel  I review the code and I find all the `__penContextsMap` in the lock by `__penContextsLock`

**Comment by Lumoryel** [comment]
You're right. I can't find code that modifies __penContextsMap without a lock.

By the way I saw that not all methods are in lock(__penContextsLock) when accessing __penContextsMap e.g. via TryGetValue().
Additionally, RefreshTablets() is enumerating the __penContextsMap without locking (e.g. called from PostProcessInput() ).

But this shouldn't be the cause for the exception.
Sure that this is the source code for .net framework 4.8 ? Where can I find this information?

**Comment by miloush** [comment]
How about this one https://github.com/dotnet/wpf/blob/368f0e850b2c9eeb7de80e1f02ddfa9257244454/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispLogic.cs#L1365

**Comment by singhashish-wpf** [comment]
@Lumoryel Do we have any more inputs on this? A TTD trace or some reliable sample repro?

**Comment by Lumoryel** [comment]
@singhashish-wpf I never saw this bug again.
What I noticed meanwhile:
On Windows 11, when you run a .NET Framework 4.8 targeted program, it actually runs Framework 4.8.1 code while on windows 10 it runs 4.8 code.

Actually I'm confused about where to look for 4.8 and 4.8.1 code?

(I had this problem here with a 4.8 framework application: https://github.com/dotnet/wpf/issues/6319)

**Comment by GSonofNun** [comment]
Just had this happen with our application. The user RDP'd from their laptop (with touch/pen support) to their desktop (without pen support) where our aplication was already running. Our app is using .NET 6, and both PCs are running Windows 11.

Unfortunately we don't have any good repro steps for it. Just wanted to mention another sighting

**Comment by GSonofNun** [comment]
I do have a minidump of the crash if it would be helpful.

**Comment by Tennyleaz** [comment]
Had this issue occurred once on my app, when a DisplayLink screen is removed from USB.
Using .net 4.7.2 on Windows 10.
