### ISSUE TITLE
when loading image and will raise COMException (0x88982F50) 

### ISSUE THREAD

**Issue by Luoyingliang** [dotnet/wpf#7254]
* .NET Core Version: net6.0 
* Windows version: (`winver`) Windows 10 or Windows 7
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* 
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/main/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
i developing an wpf app for my fans, and some fans report my app sometimes will crash when loading image, but mostly user no crash
 Warn 15:24:49.2341 | System.TypeInitializationException: The type initializer for 'Acorisoft.FutureGL.MigaStudio.StaticImageSource' threw an exception.  System.TypeInitializationException: The type initializer for 'Acorisoft.FutureGL.MigaStudio.StaticImageSource' threw an exception.
 ---> System.NotSupportedException: 未找到适用于完成此操作的图像处理组件。
 ---> System.Runtime.InteropServices.COMException (0x88982F50): 无法找不到组件。 (0x88982F50)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage.. ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.Imaging.BitmapImage.. ctor(Uri uriSource)
 **Actual behavior:** 
 
 **Expected behavior:**
 
 **Minimal repro:**

**Comment by miloush** [comment]
Google Translator:
---> System.NotSupportedException: No image processing components were found suitable for this operation.
---> System.Runtime.InteropServices.COMException (0x88982F50): Could not find component. (0x88982F50)

We can probably do without a repro here, clearly the image type is not supported by WIC here. @Luoyingliang your code should be able to deal with your users trying to load an image or any other file that is not a supported image file.

If you have a image file that you think should be supported but it is not, share the image file.

**Comment by Luoyingliang** [comment]
> @Luoyingliang - We'll need a sample repro of this issue to be able to investigate further.



> @Luoyingliang - We'll need a sample repro of this issue to be able to investigate further.

thank you , maybe this issues happen in a wired system.
now ,i resolved the  issues.
there has two posible i guess

1) anti-viru software injure app and break my assembly data
2) the wic cann't not read the memory image from assembly from  customer system 

my app setting the image in assembly as resouce, so when wpf loading the manifest stream and copy the data to decoder, wic can't recognize the image data.

so, i set the image as normal file, and copy to the application dir when every time build.when application starting we will use FileStream to load BitmapImage finally the problem is resolved

**Comment by Luoyingliang** [comment]
> * If you using a stream that you got from somewhere, make sure it's position is 0 before giving to decoder
> * This would not help if for example the image is HEIC and some of the users don't have a HEIC codec installed.

when the problem happen, i was using URI string to automatically load the image from assembly , like 'pack://application:,,,/myassembly;imagepath',this code working so well on my mostly customer and i.but there are still has a little part of customer  happen this issues.

some customer use win7 os, some are use win10 , i can't ensure whether has installed HEIC codec  , the runtime enviroment is complexity. finally i try to load the image manually and problem resolved.

maybe decoder cannot recoginzed the image format in memory.
