### ISSUE TITLE
 System.Windows.ContextLayoutManager.UpdateLayout() throws KeyNotFoundException

### ISSUE THREAD

**Issue by tripleacoder** [dotnet/wpf#7542]
### Description

I get this exception quite often in my .NET 4.8 WPF app. The error is sent from clients automatically and I do not know how to reproduce it, or from what part of the code it originates.

I found a similar issue saying it had been fixed in 4.8:
[https://github.com/dotnet/wpf/issues/2152]

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at MS.Internal.WeakDictionary`2.get_Item(TKey key)
   at System.Windows.Automation.Peers.ItemPeersStorage`1.get_Item(Object item)
   at System.Windows.Automation.Peers.ItemsControlAutomationPeer.GetChildrenCore()
   at System.Windows.Automation.Peers.ListViewAutomationPeer.GetChildrenCore()
   at System.Windows.Automation.Peers.AutomationPeer.EnsureChildren()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateChildrenInternal(Int32 invalidateLimit)
   at System.Windows.Automation.Peers.ItemsControlAutomationPeer.UpdateChildren()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Reproduction Steps

Don't know.

### Expected behavior

No exception

### Actual behavior

Program crashes?

### Configuration

.NET 4.8
Windows 10
x64

**Comment by miloush** [comment]
I can imagine this happening when the item is removed between the check and usage, classic race condition:

https://github.com/dotnet/wpf/blob/b148c5c887e11f5bc1e40c01fa319ab24852e4b1/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemsControlAutomationPeer.cs#L603-L606

That's why TryGet methods were introduced. However, looking at `WeakDictionary`, this is not doing much better either:

https://github.com/dotnet/wpf/blob/b148c5c887e11f5bc1e40c01fa319ab24852e4b1/src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/WeakDictionary.cs#L225-L229

Fix seems straightforward, but will need to touch `WeakDictionary`

**Comment by pchaurasia14** [comment]
@tripleacoder - We'll need a reliable repro or a time travel trace that can help us diagnose this further.

**Comment by tripleacoder** [comment]
OK.

Here is a longer stack trace I got today:

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at MS.Internal.WeakDictionary`2.get_Item(TKey key)
   at System.Windows.Automation.Peers.ItemPeersStorage`1.get_Item(Object item)
   at System.Windows.Automation.Peers.ItemsControlAutomationPeer.GetChildrenCore()
   at System.Windows.Automation.Peers.ListViewAutomationPeer.GetChildrenCore()
   at System.Windows.Automation.Peers.AutomationPeer.EnsureChildren()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateChildrenInternal(Int32 invalidateLimit)
   at System.Windows.Automation.Peers.ItemsControlAutomationPeer.UpdateChildren()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at MyApp.App..ctor()
   at MyApp.Main()

```

**Comment by miloush** [comment]
> Fix seems straightforward

Actually it is not that trivial. The underlying `Hashtable` does not have `TryGetValue`, so the only way to distinguish between a key not being present and a key storing null value is through `ContainsKey`. On the good side, none of the callers (which are `ItemsPeerStorage` and `KeyTipService`) distinguish between null values and key not present, so theoretically it could be fixed without changing current behavior.

The race condition is only an issue if the collection is accessed from multiple threads, which classes are not designed for by default. I support getting a repro/TTT to find out the underlying issue.

**Comment by tripleacoder** [comment]
I have still not found the cause of the error.

Some more details about the program:

It is an MVVM application without user interaction. Its purpose is to display changing data. 

The Viewmodel properties are bound to by the View. The ViewModel properties are periodically refreshed using various methods - one ViewModel uses a BackgroundWorker, another uses DispatcherTimer.

Here is some code:

```
public class ViewModel1
{

private DispatcherTimer dispatcherTimer = new DispatcherTimer();
private bool isDisposed = false;
private Model.DataLayer datalayer;
private Model.Stats[] _stats;

public ViewModel1()
{
this.dispatcherTimer.Interval = TimeSpan.FromSeconds(1);
                this.dispatcherTimer.Tick += this.dispatcherTimer_Tick;
                this.dispatcherTimer.Start();
}
public Model.Stats[] Stats
        {
            get
            {
                return this._stats;
            }

            set
            {
                this.SetProperty(ref this._stats, value);
                this.NotifyPropertyChanged(nameof(this.PickUTD1));
                this.NotifyPropertyChanged(nameof(this.PickUTD2));
            }
        }

        public List<string> PickUTD1
        {
            get
            {
                if (this.Stats == null)
                {
                    return null;
                }

                return this.Stats.Where(s => s.UTD_Area == 1 && s.Pick > 0).
                    Select(s => s.Pick + " stk. " + s.ExternProdName_Aggregate).
                    ToList();
            }
        }

        public List<string> PickUTD2
        {
            get
            {
                if (this.Stats == null)
                {
                    return null;
                }

                return this.Stats.Where(s => s.UTD_Area == 2 && s.Pick > 0).
                    Select(s => s.Pick + " stk. " + s.ExternProdName_Aggregate).
                    ToList();
            }
        }
private void dispatcherTimer_Tick(object sender, EventArgs e)
        {
            this.UpdateData();
        }

 private async void UpdateData()
        {
            this.dispatcherTimer.Stop();
            try
            {
                await this.RefreshAsync();

                this.dispatcherTimer.Interval = TimeSpan.FromMinutes(1);
            }
            catch (Exception ex)
            {
            }

            if (!this.isDisposed)
            {
                this.dispatcherTimer.Start();
            }
        }

public override async Task RefreshAsync()
        {
            this.Stats = await this.datalayer.GetStatus();
        }
}

View1.xaml:

<DataGrid Grid.Row="3" Grid.Column="0" Grid.ColumnSpan="2" ItemsSource="{Binding Stats, Mode=OneWay}" FontSize="20" AutoGenerateColumns="False" IsReadOnly="True" CanUserAddRows="False" CanUserDeleteRows="False" CanUserReorderColumns="False" CanUserSortColumns="False">
```

**Comment by tripleacoder** [comment]
Here is another code example:

```
public class ViewModel2
{
public ViewModel2()
{
BackgroundWorker bw = new BackgroundWorker();
                bw.DoWork += (s, ea) =>
                {
                    while (true)
                    {
                        this.UpdateData();
                        Thread.Sleep(TimeSpan.FromSeconds(5));
                    }
                };
                bw.RunWorkerAsync();
}

 private void UpdateData()
        {           
            try
            {
                this.RefreshFrequent();

                if ((DateTime.Now - this.wipUpdateTime).TotalMinutes > 1)
                {
                    this.RefreshSeldom();
                }

                this.lastSuccessfulUpdateTime = DateTime.Now;
            }
            catch (Exception ex)
            {
                if ((DateTime.Now - this.lastSuccessfulUpdateTime).TotalMinutes > 1)
                {
                    this.D2Info = null;
                    this.Wrap = null;
                }

                if ((DateTime.Now - this.wipUpdateTime).TotalMinutes > 2)
                {
                    this.WIPHistory = null;
                }
            }

            try
            {
                this.RefreshDraw();
            }
            catch (Exception ex)
            {
                this.Draw = null;
            }
        }

        private void RefreshSeldom()
        {
            var allWIP = this.dataClient.GetWIP();
            if (allWIP != null)
            {
                this.WIP = allWIP.PD1;
                this.WIPOverview = allWIP.Overview.PD1;

                this.WIPHistory = this.dataClient.GetWIPHistory();
                this.wipUpdateTime = DateTime.Now;
            }
        }
/* Refresh methods omitted. They simply poll DAL and set the viewmodel properties. */

}
```

**Comment by tripleacoder** [comment]
Another example:

```
public ViewModel1
{
private BitmapImage videoFrame1; 
protected IDispatcher dispatcher;

public ViewModel1(IDispatcher dispatcher)
{
   this.dispatcher = dispatcher;

   SetupVideoStream();
}

public BitmapImage VideoFrame1
        {
            get { return this.videoFrame1; }
            set { this.SetProperty(ref this.videoFrame1, value); }
        }

 private void SetupVideoStream()
        {          
            BackgroundWorker bw = new BackgroundWorker();
            bw.DoWork += (s, ea) =>
            {
                while (true)
                {
                    try
                    {
                        byte[] buffer = new byte[1000000];
                        int read, total = 0;

                        HttpWebRequest req = (HttpWebRequest)WebRequest.Create("http://");

                        req.Credentials = new NetworkCredential("aaa", "bbb");
                        using (WebResponse resp = req.GetResponse())
                        using (Stream stream = resp.GetResponseStream())
                        {
                            while ((read = stream.Read(buffer, total, 1000)) != 0)
                            {
                                total += read;
                            }
                        }

                        using (Bitmap bmp = (Bitmap)Bitmap.FromStream(new MemoryStream(buffer, 0, total)))
                        using (Bitmap small = ResizeImage(bmp, 640, (int)(bmp.Height * (640.0 / bmp.Width))))
                        {
                            this.dispatcher.Invoke(() => this.ArnoldiLockFrame = this.BitmapToImageSource(small));
                        }
                    }
                    catch (Exception ex)
                    {
                    }

                    Thread.Sleep(TimeSpan.FromMinutes(1));
                }
            };
            bw.RunWorkerAsync();
        }

}

internal class UIDispatcher : IDispatcher
    {
        public void Invoke(Action callback)
        {
            System.Windows.Application.Current.Dispatcher.Invoke(callback);
        }
    }

<Image Source="{Binding Path=VideoFrame1}" />
```

**Comment by miloush** [comment]
@tripleacoder better to provide a project that people can run, I don't think these examples are that insightful

**Comment by tripleacoder** [comment]
> @tripleacoder better to provide a project that people can run, I don't think these examples are that insightful

Unfortunately I cannot even reproduce the bug on my own computer.

**Comment by ZeeNastalski** [comment]
We also have this problem. Our WPF application crashes at random. We tried updating .NET Framework from 4.7.2 to 4.8 but it didn't help. Our application also extensively uses DispatchTimer, Dispatcher.Invoke() and we also rely heavily on async/await for I/O operations.

Unfortunately, I can't provide reliable reproduction at this time. Our application crashes roughly once per day which makes it impossible to ship, yet very hard to diagnose. 


Any help or suggestions would be much appreciated.

@tripleacoder, did you have any success with this issue?

```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException
   at MS.Internal.WeakDictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(System.__Canon)
   at System.Windows.Automation.Peers.ItemPeersStorage`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(System.Object)
   at System.Windows.Automation.Peers.ItemsControlAutomationPeer.GetChildrenCore()
   at System.Windows.Automation.Peers.ListViewAutomationPeer.GetChildrenCore()
   at System.Windows.Automation.Peers.AutomationPeer.EnsureChildren()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateChildrenInternal(Int32)
   at System.Windows.Automation.Peers.ItemsControlAutomationPeer.UpdateChildren()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at App.Main()
```

**Comment by tripleacoder** [comment]
> We also have this problem. Our WPF application crashes at random. We tried updating .NET Framework from 4.7.2 to 4.8 but it didn't help. Our application also extensively uses DispatchTimer, Dispatcher.Invoke() and we also rely heavily on async/await for I/O operations.
> 
> Unfortunately, I can't provide reliable reproduction at this time. Our application crashes roughly once per day which makes it impossible to ship, yet very hard to diagnose.
> 
> Any help or suggestions would be much appreciated.
> 
> @tripleacoder, did you have any success with this issue?
> ```

I never solved it. 
Instead I have made a workaround that simply ignores the exception in my global exception handling code:

```
private void HandleUnhandledExceptions(DispatcherUnhandledExceptionEventArgs e)
        {
            e.Handled = false; // true; // program lives, false = windows will close it

            Exception exception = e.Exception;

            if (exception is System.Collections.Generic.KeyNotFoundException)
            {
                if (exception.StackTrace.Contains("System.Windows.Automation.Peers.ItemPeersStorage"))
                {
                    // This exception is described here:
                    // https://dev.azure.com/REDACTED/_workitems/edit/4094
                    // Cause: unknown.
                    // It does not affect the user in any way, so we can just ignore it. Don't send any emails to the dev either.
                    e.Handled = true;
                }
                else
                {
                    this.vm.HandleUserException(exception, false);
                }
            }
            else
            {
                this.vm.HandleUserException(exception, true);
            }
        }
```

**Comment by rkeithhill-keysight** [comment]
We also see this issue randomly crash our WPF app:
```
Exception 1: System.Collections.Generic.KeyNotFoundException
Message:  The given key was not present in the dictionary.
Source:   PresentationFramework
Site:     TValue get_Item(TKey)
System.Object: 
   *** Stack Trace ***
   at MS.Internal.WeakDictionary`2.get_Item(TKey key)
   at System.Windows.Automation.Peers.ItemPeersStorage`1.get_Item(Object item)
   at System.Windows.Automation.Peers.ItemsControlAutomationPeer.GetChildrenCore()
   at System.Windows.Automation.Peers.ListViewAutomationPeer.GetChildrenCore()
   at System.Windows.Automation.Peers.AutomationPeer.EnsureChildren()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateChildrenInternal(Int32 invalidateLimit)
   at System.Windows.Automation.Peers.ItemsControlAutomationPeer.UpdateChildren()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by ZeeNastalski** [comment]
@rkeithhill-keysight, the workaround offered by tripleacoder worked for me. I don't see any side effects of simply catching and ignoring this exception in my application.
