### ISSUE TITLE
PopupSecurityHelper.ForceMsaaToUiaBridge causes FileNotFoundException

### ISSUE THREAD

**Issue by RandomEngy** [dotnet/wpf#7751]
### Description

I've gotten several reports from users that crash with this exception:

```
System.IO.FileNotFoundException: 
File name: 'Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Windows.Controls.Primitives.Popup.PopupSecurityHelper.ForceMsaaToUiaBridge(PopupRoot popupRoot)
   at System.Windows.Controls.Primitives.Popup.CreateWindow(Boolean asyncCall)
   at System.Windows.Controls.Primitives.Popup.OnIsOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   ...
```

https://github.com/RandomEngy/VidCoder/issues/1093, https://github.com/RandomEngy/VidCoder/issues/1136

It happens on a popup, in one case with a tooltip and in another case on a menu dropdown using the Fluent Ribbon WPF library. I've never seen this happen; and these actions are quite common in regular usage of the program.

Maybe addressing https://github.com/dotnet/wpf/issues/5807 would fix this?

### Reproduction Steps

Open a popup (not consistent)

### Expected behavior

No crash

### Actual behavior

Crash with FileNotFound exception

### Configuration

.NET 6.0
x64
I don't know if it's specific to this configuration; I've only gotten a few bug reports.

**Comment by singhashish-wpf** [comment]
@RandomEngy is it possible to share a minimal reliable repro for this?

**Comment by RandomEngy** [comment]
I've never reproduced this; I've only gotten reports from my users. It seems to happen when opening a pop-up, but it's not a reliable repro.

**Comment by singhashish-wpf** [comment]
@RandomEngy Thanks for the quick response. I might be asking for more, but a TTD or a machine with a reliable repro would be required to act on this further in my understanding. This is also important to verify the fix if we have it in future. Can we do something here to get the TTD?

**Comment by RandomEngy** [comment]
I could add some code to collect additional information on the crash, but as I said there is no known reliable repro. I do realize that makes fixing it more difficult; though I hope not impossible, given you have the stack traces.

In the past I have been able to fix issues like these without reproducing them personally, and I hope it's something you can accomplish in this case.

**Comment by JBrownie77** [comment]
+1 - we have been having customers hit this but don't have a reliable repro yet either

**Comment by mike-laws** [comment]
We experienced this same issue today. It looks to be a slightly different stack trace but the same issue as reported. Posting it here incase it's of any help.

```
{"@t":"2023-10-30T10:00:17.6672572Z","@mt":"Fatal error: {Message} {StackTrace}","@l":"Fatal","Message":"Cannot save value from target back to source. BindingExpression:Path=IsDropDownOpen; DataItem='IconMenu' (Name=''); target element is 'ToggleButton' (Name='toggleButton'); target property is 'IsChecked' (type 'Nullable`1') FileNotFoundException:'System.IO.FileNotFoundException: Could not load file or assembly 'Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Den angivne fil blev ikke fundet.
File name: 'Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Windows.Controls.Primitives.Popup.PopupSecurityHelper.ForceMsaaToUiaBridge(PopupRoot popupRoot)
   at System.Windows.Controls.Primitives.Popup.CreateWindow(Boolean asyncCall)
   at System.Windows.Controls.Primitives.Popup.OnIsOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.OnDependencyPropertyChanged(DependencyObject d, DependencyProperty dp, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at MS.Internal.Data.PropertyPathWorker.SetValue(Object item, Object value)
   at MS.Internal.Data.ClrBindingWorker.UpdateValue(Object value)
   at System.Windows.Data.BindingExpression.UpdateSource(Object value)'","StackTrace":"   at CathVision.Cube.RecorderApp.Utils.AppErrorHandler.GetFullStackTrace()
   at CathVision.Cube.RecorderApp.Utils.AppErrorHandler.OnFatalError(String message)
   at CathVision.Cube.RecorderApp.Utils.BindingErrorTraceListener.WriteLine(String message)
   at System.Diagnostics.TraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String format, Object[] args)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
   at MS.Internal.AvTrace.Trace(TraceEventType type, Int32 eventId, String message, String[] labels, Object[] parameters)
   at MS.Internal.TraceData.TraceAndNotify(TraceEventType eventType, AvTraceDetails traceDetails, BindingExpressionBase binding, Exception exception)
   at System.Windows.Data.BindingExpression.UpdateSource(Object value)
   at System.Windows.Data.BindingExpressionBase.UpdateValue()
   at System.Windows.Data.BindingExpressionBase.ProcessDirty()
   at System.Windows.Data.BindingExpressionBase.Dirty()
   at System.Windows.Data.BindingExpressionBase.SetValue(DependencyObject d, DependencyProperty dp, Object value)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.Primitives.ToggleButton.OnToggle()
   at System.Windows.Controls.Primitives.ToggleButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at CathVision.Cube.RecorderApp.App.Main()
","SourceContext":"CathVision.Cube.RecorderApp.Utils.AppErrorHandler","ThreadId":1,"ThreadName":"Review window"}
```

**Comment by lindexi** [comment]
@mike-laws Can you find the repro step?

**Comment by RandomEngy** [comment]
> We also have no repro scenario

**Comment by moellerm** [comment]
You can reproduce this if you start a WPF application, then upgrade the dotnet (desktop) runtime in another session (for example from 6.0.22 to 6.0.24) and then come back to the session with the WPF application running. Accessing the application with the Narrator (Microsoft screen reader app) usually triggers the exception. You won't get the exception if the Accessibility.dll was already loaded in the application before upgrading the dotnet runtime, 

The same issue can occur if Windows Update upgrades the dotnet runtime in the background while the WPF application is running, or if you uninstall the dotnet runtime in another session. There is an issue https://github.com/dotnet/runtime/issues/60144 with more details about the dotnet runtime installer problem.

**Comment by emergencynap** [comment]
Still seeing this, exactly as described above.

**Comment by lindexi** [comment]
```
System.DllNotFoundException
Unable to load DLL 'oleacc.dll' or one of its dependencies:  (0x8007045A)

int UnsafeNativeMethods.ObjectFromLresult(IntPtr lResult, ref Guid iid, IntPtr wParam, out IAccessible ppvObject)
void PopupSecurityHelper.ForceMsaaToUiaBridge(PopupRoot popupRoot)
void Popup.CreateWindow(bool asyncCall)
```
