### ISSUE TITLE
[8.0.100-preview.7.23376.3] NETworkManager Cannot add null to the collection error when trying to open dialog with MahApps library

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/wpf#8070]
### Description

Starting from dotnet-sdk-8.0.100-preview.5.23264.1, NETworkManager gets this error when it opens a dialog MahApps
```
Exception Info: System.ArgumentException: Cannot add null to the collection.
   at System.Windows.Media.GeneralTransformCollection.AddWithoutFiringPublicEvents(GeneralTransform value)
   at System.Windows.Media.GeneralTransformCollection.Add(GeneralTransform value)
```

### Reproduction Steps

**Repro steps**:

1) Run the app with .net8 by updating NETworkManager.runtimeconfig.
```
 "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "8.0.0-preview.7.23375.6"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "8.0.0-preview.7.23376.1"
      }
```
2) launch the app NETworkManager.exe.
3) Click the Continue button if you see it.
4) Click any icon from the left menu.
5) Click "No Profile found, create one ..." like below screenshot.

![screenshot1](https://github.com/dotnet/wpf/assets/83067197/d9c8d10a-cf9f-4161-aed2-7995d5237aca)

### Expected behavior

Displays create profile dialog.

### Actual behavior

The app stops working.

Exception:
```
Application: NETworkManager.exe
CoreCLR Version: 8.0.23.37506
.NET Version: 8.0.0-preview.7.23375.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Cannot add null to the collection.
   at System.Windows.Media.GeneralTransformCollection.AddWithoutFiringPublicEvents(GeneralTransform value)
   at System.Windows.Media.GeneralTransformCollection.Add(GeneralTransform value)
   at MS.Internal.Controls.TemplatedAdorner.GetDesiredTransform(GeneralTransform transform)
   at System.Windows.Documents.AdornerLayer.ArrangeOverride(Size finalSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.ScrollContentPresenter.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Control.ArrangeOverride(Size arrangeBounds)
   at System.Windows.Controls.ScrollViewer.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at MS.Internal.Helper.ArrangeElementWithSingleChild(UIElement element, Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Border.ArrangeOverride(Size finalSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Control.ArrangeOverride(Size arrangeBounds)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at MS.Internal.Helper.ArrangeElementWithSingleChild(UIElement element, Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Border.ArrangeOverride(Size finalSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Control.ArrangeOverride(Size arrangeBounds)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at MS.Internal.Helper.ArrangeElementWithSingleChild(UIElement element, Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Control.ArrangeOverride(Size arrangeBounds)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at NETworkManager.App.Main()

```

### Regression?

Yes

**Verify Scenarios:**
1. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.5.23364.1: Fail
2. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.5.23265.7: Fail
3. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.5.23269.37: Fail
4. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.5.23281.8: Fail
5. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.6.23303.5: Fail
6. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.6.23330.14: Fail
7. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.7.23376.3: Fail
8. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.5.23228.7: Pass
9. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.1.23103.1: Pass
10. Windows10 21h2 x64 + dotnet-sdk-6.0.413-win-x64: Pass
11. Windows10 21h2 x64 + dotnet-sdk-7.0.110-win-x64: Pass

### Configuration

**Application Name**: NETworkManager
**OS**： Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-8.0.100-preview.7.23376.3
**App Github Link**: https://github.com/BornToBeRoot/NETworkManager
**App, App Source, or Repro machine checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1864961

### Other information

**Findings:**
When we click add profile button, it displays ProfileDialog usercontrol using Mahapps library ShowMetroDialogAsync method, we noticed when we remove the ValidationRules  bindings in UserControl, error does not repro, like this:
```
 <ComboBox x:Name="ComboBoxGroup" Grid.Column="2" Grid.Row="4" Style="{StaticResource EditableComboBox}">
                                    <ComboBox.Text>
                                        <Binding Path="Group">
                                            <Binding.ValidationRules>
                                                 <!--Remove this Part-->
                                                <!--<validators:EmptyValidator ValidatesOnTargetUpdated="True" />-->
                                                <!--<validators:GroupNameValidator ValidatesOnTargetUpdated="True" />-->
                                            </Binding.ValidationRules>
                                        </Binding>
                                    </ComboBox.Text>
                                </ComboBox>

```
@dotnet-actwx-bot @dotnet/compat

**Comment by singhashish-wpf** [comment]
@batzen - Looks like this is an unintended consequence of this PR (https://github.com/dotnet/wpf/pull/1167)
We are investigating the root cause and will keep this thread posted of updates. 
PS - In case. we are unable to come up with a fix within the release schedule, we may have to consider reverting this PR.

**Comment by batzen** [comment]
I don't think reverting the PR is the correct solution here.
The code in `TemplatedAdorner.GetDesiredTransform` is clearly wrong because it does not check if there was any transform provided.
Other adorner classes check the supplied transform, while others don't.
Classes that check for null:
- `ColumnResizeAdorner`
- `CompositionAdorner` (checks after it access members of the transform, so it will crash with NRE)
- `InkCanvasFeedbackAdorner` (checks but throws an argument exception)

Classes that don't check for null:
- `TemplatedAdorner`
- `AnnotationAdorner` (just forwards to other annotation components)

Annotation components:
- `StickyNoteControl` (does not check for null)

So developers were kind of aware that the transform might be null.
As the code inside `Adorner` does not guarantee that `AdornerInfo` has a transform, it would be way better the add null checks where they are missing.

This is another example of where nullable annotations would help a lot, as `GetDesiredTransform` would have the proper annotation. And as `AdornerInfo` can have a null transform, that annotation would have told us so.

**Comment by batzen** [comment]
Haven't debugged yet.
Will do that after my vacation.
So I will post my results here in about two weeks, if that's ok @singhashish-wpf

**Comment by batzen** [comment]
So I was lucky and found some time to investigate this before my vacation.

I can also repro the same exception, using different code, on .NET 7.0 (which does not have my changes).
The issue here really comes down to missing null checks, at least that's my opinion.

See the attached repro project.
[adorner_test.zip](https://github.com/dotnet/wpf/files/12290305/adorner_test.zip)

@miloush @singhashish-wpf @Junjun-zhao

**Comment by pchaurasia14** [comment]
@Junjun-zhao - We've fixed this in upcoming .NET 8 RC1. Request you to please retest this.

**Comment by Junjun-zhao** [comment]
@pchaurasia14 We've checked it on today's build dotnet-sdk-8.0.100-rc.1.23412.1, it is still repro. We will verify it on the newer .NET 8 RC1 build and keep you posted.

**Comment by Junjun-zhao** [comment]
Verified this issue on latest dotnet-sdk-8.0.100-rc.1.23415.7, it has been fixed. Hence closing it.
