### ISSUE TITLE
System.ArgumentNullException in System.Windows.UIElement.AddHandler(DependencyObject d, RoutedEvent routedEvent, Delegate handler)

### ISSUE THREAD

**Issue by matthew-a-thomas** [dotnet/wpf#8106]
### Description

Here's the observed stack trace:

```
Type: System.ArgumentNullException
Message: Value cannot be null. (Parameter 'd')
Source: PresentationCore
Stack Trace:
   at System.Windows.UIElement.AddHandler(DependencyObject d, RoutedEvent routedEvent, Delegate handler)
   at System.Windows.UIElement.OnIsVisibleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.UIElement.UpdateIsVisibleCache()
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.OnDependencyPropertyChanged(DependencyObject d, DependencyProperty dp, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.OnDependencyPropertyChanged(DependencyObject d, DependencyProperty dp, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

### Reproduction Steps

Sorry, not repro is available. This was observed once in the wild through our app's exception reporting.

### Expected behavior

An exception should not be thrown

### Actual behavior

In fact an exception is thrown

### Regression?

Unknown

### Impact

Low impact so far. Only one occurrence observed so far.

### Configuration

OS Version: Microsoft Windows 10.0.19044
Runtime: .NET 6.0.14
x64

I don't know if it's specific to this configuration

### Other information

Sorry, that's all I've got

**Comment by matthew-a-thomas** [comment]
It seems unlikely to me, too.

On the other hand I can't help but notice all the null checks in `TextCompositionManager`:
* `AddPreviewTextInputStartHandler`
* `AddTextInputStartHandler`
* `AddPreviewTextInputUpdateHandler`
* `AddTextInputUpdateHandler`
* `AddPreviewTextInputHandler`
* `AddTextInputHandler`

So maybe that's a clue? The git history doesn't go back far enough so I'm merely speculating.

Another mystery to me is how the stack frames jump from `UIElement.OnIsVisibleChanged` to `UIElement.AddHandler`. Has the JIT become that aggressive in inlining stuff?
* Either it got there through `UIElement.RaiseDependencyPropertyChanged(EventPrivateKey key, DependencyPropertyChangedEventArgs args)`
  * But that involves a dynamic dispatch through a `Delegate`
* Or else it got there through `Visual.InvalidateForceInheritPropertyOnChildren(DependencyProperty property)`
  * But that's a virtual method call

**Comment by matthew-a-thomas** [comment]
If you're able to narrow down the possibilities for me, like if you think it might be one of our value converters or markup extensions or ..., then I'm more than happy to investigate our codebase to help you determine if this is truly a WPF bug or merely some strange interaction outside your control. But I'll need your help pointing me in the right direction. All I have at the moment is that strange stack trace.

**Comment by Kuldeep-MS** [comment]
@matthew-a-thomas Providing us with the time travel trace for the issue would be helpful as it may be difficult to solely debug the issue through the stack trace.
