### ISSUE TITLE
ArgumentNullException in UIElementAutomationPeer

### ISSUE THREAD

**Issue by clovett** [dotnet/wpf#8188]
### Description

I get the following stack trace entirely in WPF (none of my code on the stack) when completing the edit of a DataGrid in a popup tool window, here I entered the new row "Votes", tabbed to enter "2" then mouse clicked on "give raises" cell above to commit the edit and boom:

![image](https://github.com/dotnet/wpf/assets/3336415/932b894e-3b17-4ef2-a02f-3f8004c027a4)

````
System.ArgumentNullException

Value cannot be null. (Parameter 'element')

System.ArgumentNullException: Value cannot be null. (Parameter 'element')
   at System.Windows.Automation.Peers.UIElementAutomationPeer.FromElement(UIElement element)
   at System.Windows.Controls.DataGrid.CellAutomationValueHolder.TrackValue()
   at System.Windows.Controls.DataGrid.ReleaseCellAutomationValueHolders()
   at System.Windows.Controls.DataGrid.OnExecutedCommitEdit(ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at System.Windows.Input.RoutedCommand.Execute(Object parameter, IInputElement target)
   at System.Windows.Controls.DataGrid.EndEdit(RoutedCommand command, DataGridCell cellContainer, DataGridEditingUnit editingUnit, Boolean exitEditMode)
   at System.Windows.Controls.DataGrid.OnCurrentCellChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.DataGrid.set_CurrentCellContainer(DataGridCell value)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyPropertyKey key, Object value)
   at System.Windows.Input.FocusManager.OnFocusedElementChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Input.KeyboardNavigation.UpdateFocusedElement(DependencyObject focusTarget)
   at System.Windows.FrameworkElement.OnGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at System.Windows.Controls.DataGridCell.OnAnyMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
````

### Reproduction Steps

[WpfPropertyWindowBug.zip](https://github.com/dotnet/wpf/files/12553747/WpfPropertyWindowBug.zip)

1. Load the attached solution
2. Press F5
3. open the "Edit" menu and select "Properties"
4. Add a new row containing "Vote" and "0"
5. Mouse click the row above to commit this new row.

### Expected behavior

The new row should commit without any unhandled exceptions.

### Actual behavior

unhandled ArgumentNullException crashes the app.  The CellAutomationValueHolder should just do some null checks before calling the UIElementAutomationPeer.FromElement function.

### Regression?

Did not happen on the .NET 4.8 version of the same code.

### Known Workarounds

None.

### Impact

Severe, major functionality with DataGrid does not work when there are automation peers involved on the data context and there is no workaround.

### Configuration

7.0.400
Windows 11 22h2, 22621.2134
x64
no idea if it is specific to this version, could be specific to windows though, not sure other platforms have automation peers?

**Comment by harshit7962** [comment]
The TrackValue method in datagrid.cs is not implementing a null check prior to calling the FromElement method of DataGridAutomationPeer. The issue is observable in dotnet 7, but is fixed in dotnet 8. The PR fixing the issue is [here](https://github.com/dotnet/wpf/pull/6553/files). We would appreciate it if you could kindly test the provided application in dotnet 8 to verify the resolution. Additionally, if there is a critical need for this fix to be included in dotnet 7, please provide a formal business case/impact outlining the necessity, and we will evaluate the possibility of backporting the solution.

**Comment by clovett** [comment]
I installed dotnet 8 rc1, and vs 2022 preview so I could build it and it seems to be fixed there.

I would like it back-ported to dotnet 7 since my customers cannot move to dotnet 8 for some time and this is a serious bug with no known work-arounds.  The [fix ](https://github.com/dotnet/wpf/pull/6553/files) also looks very simple and contained reducing the risk of having any negative effect on dotnet 7, simply adding null checks.

**Comment by Torsteinws** [comment]
I have the exact same problem on my end.

It would be really great if you back-ported it to dotnet 7 as I will not be able to move to dotnet 8 for some time, and my customers are already getting mildly annoyed about this issue.

If back-port is impractical or not possible, I would be really happy if someone would write up a workaround for it.

**Comment by Torsteinws** [comment]
I believe #5900 is related

**Comment by singhashish-wpf** [comment]
@Torsteinws  @clovett  Any changes to the servicing branches would require proper business impact and justification in real numbers. We understand that this fix is required to be backported and we are supportive of it. The details of impact justification will make it certain for the fix to be merged. So kindly help with any data in support of the impact of the bug.

**Comment by Torsteinws** [comment]
I understand. Unfortunately, I am not in a position were I can give out that information about my company. I am sorry.

**Comment by clovett** [comment]
I would say the severity of the bug is the business justification here.  It is a very bad bug.

**Comment by harshit7962** [comment]
@Torsteinws @clovett we have backported the required change in release/7.0. It should be available in the next service release.

**Comment by poullj** [comment]
> @Torsteinws @clovett we have backported the required change in release/7.0. It should be available in the next service release.

Does this means that it is fixed in 7.0.15 ?

**Comment by harshit7962** [comment]
@poullj Yes this fix is available since release of 7.0.14. 
@clovett Can we also confirm if it solves your issue.

**Comment by YuuukiA** [comment]
@harshit7962, @singhashish-wpf
Hello,
Do you have any update?

**Comment by YuuukiA** [comment]
@harshit7962, @singhashish-wpf
Hello,
Do you have any update?

**Comment by YuuukiA** [comment]
@harshit7962, @singhashish-wpf
Hello,
Do you have any update?

**Comment by h3xds1nz** [comment]
Fixed in #8477, .NET 6 is out of support.
