### ISSUE TITLE
error MC1000: Unknown build error, 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by matthew-a-thomas** [dotnet/wpf#8394]
### Description

WPF/XAML project fails to build with this error:
> error MC1000: Unknown build error, 'Object reference not set to an instance of an object.'

Detailed build log is here:

https://raw.githubusercontent.com/matthew-a-thomas/dotnet-error-mc1000/7cb13040dd16ffff5a772a288fc7c1972abb582c/log.txt

Everything builds fine if `<Node>` is empty (in `Example.xaml`):

```xml
<Node xmlns="clr-namespace:WpfApp7">delete these contents of "Node" to make it compile</Node>
```

### Reproduction Steps

https://github.com/matthew-a-thomas/dotnet-error-mc1000/tree/7cb13040dd16ffff5a772a288fc7c1972abb582c

`dotnet build` fails with this error.

`dotnet build` succeeds if `Example.xaml` is changed to:

```xml
<Node xmlns="clr-namespace:WpfApp7"></Node>
```

### Expected behavior

Successful build

### Actual behavior

Error

### Regression?

Not sure. I tried uninstalling .NET 8 SDK and I still get the error when building with .NET 7 SDK

### Configuration

> dotnet --version
> 8.0.100-rc.2.23502.2

> dotnet --version
> 8.0.100-rc.1.23463.5

> dotnet --version
> 7.0.403

(Happens with all three of these SDKs)

Windows 11

x64

**Comment by singhashish-wpf** [comment]
`{System.NullReferenceException: Object reference not set to an instance of an object.
   at MS.Internal.Markup.XamlReaderHelper.VerifyContentPropertySeesAnElement(ElementContextStackData context)
   at MS.Internal.Markup.XamlReaderHelper.AddNodeToCollection(XamlNode xamlNode, Boolean insert, Boolean insertAtStart)
   at MS.Internal.Markup.XamlReaderHelper.AddNodeToCollection(XamlNode xamlNode)
   at MS.Internal.Markup.XamlReaderHelper.WriteDocumentEnd()
   at MS.Internal.Markup.XamlReaderHelper.Read(XamlNode& xamlNode)
   at MS.Internal.Markup.XamlParser.ReadXaml(Boolean singleRecordMode)}`


The xamlNode being evaluated for this is coming as null and due to which the above exception stack is coming up.

**Comment by carloschavez9** [comment]
Is there any update on this issue?
