### ISSUE TITLE
WPF crash while RDP login

### ISSUE THREAD

**Issue by heartacker** [dotnet/wpf#8430]
### Description

发生异常: CLR/System.ArgumentException
“System.ArgumentException”类型的未经处理的异常在 System.Private.CoreLib.dll 中发生 : '后台缓冲区的设备无效。'
 发现内部异常，有关更多详细信息，请参阅变量窗口中的 $exception。
 最里面的异常 	 System.Runtime.InteropServices.COMException : 0x88980803

### Reproduction Steps

- run a wpf in pc-A
- login RDP using pc-B
- WPF APP crash 

### Expected behavior

OK

### Actual behavior

![a4f912f232ba8748db7af0e0b92d6bc](https://github.com/dotnet/wpf/assets/1876302/8d39430d-3596-4b5f-9916-47ae54734575)

### Known Workarounds

NULL

### Impact

danger
risk

**Comment by singhashish-wpf** [comment]
@heartacker can you provide a minimal repro app? Or this is happening with any sample wpf app as well?

**Comment by heartacker** [comment]
> @heartacker I've had this problem before, due to a graphics card driver issue.
> 
> 我之前遇到过这样的问题，原因是显卡驱动问题

感谢，我需要咋做，我也没见到更新，驱动更新也没有

**Comment by lindexi** [comment]
@heartacker Can you test more computers? I think it's a strange question. 

能否多测试其他的电脑？如果驱动啥的都正常，那就太无解了。我遇到过的只有显驱有问题才会导致这个问题，现在我也缺乏更多的信息，无法给出什么建议。也不排除可能多安装了一些奇怪的应用劫持了 D3D 层

**Comment by lindexi** [comment]
The other reference issues: https://lightningchart.com/forum/viewtopic.php?t=2575#p7207

Exception:

```
System.ArgumentException: Back buffer's device is not valid. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x88980803
--- End of inner exception stack trace ---
at System.Windows.Interop.D3DImage.SetBackBuffer(D3DResourceType backBufferType, IntPtr backBuffer, Boolean enableSoftwareFallback)
at Arction.RenderingEngine11.RenderingEngine11.OnWpfImageChange()
at Arction.RenderingEngine.RenderingEngineBase.SetWPFImage(Object image)
at Arction.Wpf.SemibindableCharting.LightningChartUltimate.LOD()
at Arction.Wpf.SemibindableCharting.LightningChartUltimate.NWC(EngineMessageInfo A)
at Arction.RenderingEngine.RenderingEngineBase.set_FrontBufferAvailable(Boolean value)
at Arction.RenderingEngine.RenderingEngineBase.OnIsFrontBufferAvailableChanged(Object sender, DependencyPropertyChangedEventArgs e)
at System.Windows.Interop.D3DImage.IsFrontBufferAvailablePropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
at System.Windows.Freezable.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
at System.Windows.DependencyObject.SetValue(DependencyPropertyKey key, Object value)
at System.Windows.Interop.D3DImage.SetIsFrontBufferAvailable(Object isAvailableVersionPair)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

> Our tester told me, that he executed application via RDP, then, after few days, logged in into computer locally (no via RDP) and after login, he saw this issue above.

**Comment by lindexi** [comment]
@heartacker Could you test the `EnableHardwareAccelerationInRdp` with dotnet 8 runtime? See https://github.com/dotnet/wpf/issues/3215

能否试一下切到 dotnet 8 的**运行时**跑跑看，同时打开 EnableHardwareAccelerationInRdp 属性，打开方法请看 [dotnet 8 WPF 支持在 RDP 远程桌面状态下启用渲染硬件加速 - lindexi - 博客园](https://www.cnblogs.com/lindexi/p/17756214.html )

打开之后可以在 RDP 下使用硬件渲染，如此可以测试更多的问题

**Comment by heartacker** [comment]
> @heartacker Could you test the `EnableHardwareAccelerationInRdp` with dotnet 8 runtime? See https://github.com/dotnet/wpf/issues/3215
> 
> 能否试一下切到 dotnet 8 的**运行时**跑跑看，同时打开 EnableHardwareAccelerationInRdp 属性，打开方法请看 [dotnet 8 WPF 支持在 RDP 远程桌面状态下启用渲染硬件加速 - lindexi - 博客园](https://www.cnblogs.com/lindexi/p/17756214.html )
> 
> 打开之后可以在 RDP 下使用硬件渲染，如此可以测试更多的问题

这个试过。还是不行

**Comment by omariom** [comment]
@heartacker  @lindexi  Can you pls use English.

**Comment by lindexi** [comment]
@omariom Sorry, but have you noticed that I use two languages?
