### ISSUE TITLE
Issue with System.Environment.FailFast failure on release/6.0 branch (version 6.0.26)

### ISSUE THREAD

**Issue by lindexi** [dotnet/wpf#8507]
I recently pulled the release/6.0 branch, specifically version 6.0.26, to build a private DEBUG version for my testing work. However, I encountered an issue where the application would fail due to System.Environment.FailFast. 

Here is the stack trace of the failure code:

```
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: DependencyProperties can only be set on DependencyObjects
   at MS.Internal.Helper.CheckCanReceiveMarkupExtension(MarkupExtension markupExtension, IServiceProvider serviceProvider, DependencyObject& targetDependencyObject, DependencyProperty& targetDependencyProperty)
   at System.Windows.Data.BindingBase.ProvideValue(IServiceProvider serviceProvider)
   at Cvte.Windows.ResourceKeyBindingExtension.ProvideValue(IServiceProvider serviceProvider)
   at System.Windows.TemplateContent.TrySharingValue(DependencyProperty property, Object value, String parentName, XamlReader xamlReader, Boolean allowRecursive, Nullable`1& sharedValue)
   at System.Windows.TemplateContent.TrySharingProperty(XamlReader xamlReader, XamlType parentType, String parentName, FrugalObjectList`1 previousNamespaces, Nullable`1& sharedValue)
   at System.Windows.TemplateContent.ParseNode(XamlReader xamlReader, StackOfFrames stack, List`1 sharedProperties, Int32& nameNumber, Object& newValue)
   at System.Windows.TemplateContent.ParseNodes(StackOfFrames stack, List`1 sharedProperties, Int32& nameNumber)
   at System.Windows.TemplateContent.ParseTree(StackOfFrames stack, List`1 sharedProperties, Int32& nameNumber)
   at System.Windows.TemplateContent.ParseXaml()
   at System.Windows.FrameworkTemplate.set_Template(TemplateContent value)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_FrameworkTemplate_Template>b__277_0(Object target, Object value)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   at System.Xaml.XamlObjectWriter.SetValue(Object inst, XamlMember property, Object value)
   at System.Xaml.XamlObjectWriter.Logic_ApplyPropertyValue(ObjectWriterContext ctx, XamlMember prop, Object value, Boolean onParent)
   at System.Xaml.XamlObjectWriter.Logic_DoAssignmentToParentProperty(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteEndMember()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
```

At the moment, I'm not sure what the root cause of this issue is. It's possible that this issue might not occur in the actual production release, but I thought it would be best to bring this to your attention. 

I would appreciate any guidance or assistance in resolving this issue. 

Thank you for your time and help.

Best regards,

**Comment by lindexi** [comment]
The Environment.FailFast is from Debug.Assert, see

https://github.com/dotnet/wpf/blob/8ea763793e7cd16b3eccfb6d5141f170326805cf/src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Helper.cs#L599-L605

And the `targetObject` is `System.Windows.SharedDp`.

**Comment by singhashish-wpf** [comment]
@lindexi Thanks for reporting this. Could you help with reproduction steps and minimal repro or TTD if you have it handy?

**Comment by lindexi** [comment]
Thank you @singhashish-wpf  I am investigating this issues. If there is any progress, I will let you know immediately.

**Comment by lindexi** [comment]
@singhashish-wpf I find the repro demo code, and I upload the code to https://github.com/lindexi/lindexi_gd/tree/79d8ed60d9d9f25e2f70a33b5f0e47f91ddf2b28/BairliqeegeaLearkanalljur

I will test the other dotnet version. I think it may not be introduced in the current version.
