### ISSUE TITLE
System.Xaml.SafeSecurityHelper.CleanupCollectedAssemblies OOM will break the application process

### ISSUE THREAD

**Issue by lindexi** [dotnet/wpf#8857]
### Description

The System.Xaml.SafeSecurityHelper.CleanupCollectedAssemblies method will collect the assembly in GCNotificationToken. However, memory needs to be allocated during the cleanup task which may throw System.OutOfMemoryException. As we know from the features of dotnet, any uncaught exception thrown in the background thread will cause the process to crash.

### Reproduction Steps

When the memory is insufficient, raise System.Xaml.SafeSecurityHelper.CleanupCollectedAssemblies method.

### Expected behavior

The cleanup task fail when the memory is insufficient, but not cause the application process to crash.

### Actual behavior

The application process crash with the stacktrace:

```
System.OutOfMemoryException
   at System.Xaml.SafeSecurityHelper.CleanupCollectedAssemblies(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback(); 
```

**Comment by lindexi** [comment]
As we can see, the System.Xaml.SafeSecurityHelper.CleanupCollectedAssemblies method need allocate the `List` in: 

https://github.com/dotnet/wpf/blob/a199f1e90717fabb31a6fd95d867ac313cfd148e/src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/SafeSecurityHelper.cs#L220

**Comment by lindexi** [comment]
@miloush I understand your point, but this would result in us being unable to create a stable application. Our application would not provide a sense of security to users. Imagine, if you were using a text editor, working on a masterpiece, and suddenly, your text editor crashes. At the same time, your inspiration dissipates into the memory, how frustrating that would be. However, if the program doesn't crash, but just behaves incorrectly, perhaps developers could take some remedial measures, avoiding such a significant loss to the user.
