### ISSUE TITLE
IValueConverter does not support nullable contexts

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#9301]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IValueConverter-does-not-support-nullabl/10485692)._

---
System.Windows.Data.IValueConverter is also available in nullable contexts.

interface IValueConverter {
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture);
    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture):
  }

However, the value and parameter arguments across the Convert(), ConvertVack() functions can be NULL, and the return value can also be NULL.

interface IValueConverter {
    public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture);
    public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture):
  }

It must be.

---
#### Feedback Bot on 10/8/2023, 06:47 AM: 

(private comment, text removed)
#### Feedback Bot on 2/5/2024, 00:15 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by miloush** [comment]
It is not clear to me what is author asking for.

```C#
    public class C : IValueConverter
    {
        public object? Convert(object? value, Type? targetType, object? parameter, CultureInfo? culture)
        {
            throw new NotImplementedException();
        }

        public object? ConvertBack(object? value, Type? targetType, object? parameter, CultureInfo? culture)
        {
            throw new NotImplementedException();
        }
    }
```

compiles just fine. If this is about nullable annotations, then it's duplicate of #7563

**Comment by alraseensaad** [comment]
I guess asking for this

System.Windows.Data Error: 7 : ConvertBack cannot convert value '' (type 'String'). BindingExpression:Path=BillNum; DataItem='CustomerDebitLedger' (HashCode=38730439); target element is 'TextBox' (Name=''); target property is 'Text' (type 'String') FormatException:'System.FormatException: The input string '' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Windows.Data.BindingExpression.ConvertBackHelper(IValueConverter converter, Object value, Type sourceType, Object parameter, CultureInfo culture)'

```xml
<TextBox Text="{Binding BillNum, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />
```
```c#
private int? billNum;
public int? BillNum
{
    get => billNum;
    set
    {
        if (SetProperty(ref billNum, value))
        {
            creditSale.InvoiceNumber = value;
        }
    }
}
```

https://github.com/user-attachments/assets/459f84db-28d5-4d9e-824f-3cfc10bda3d4

**Comment by miloush** [comment]
Not really, does that work with non-nullable property? The issue in this case is that you cannot convert from empty string to a number.
