### ISSUE TITLE
Crash When Oculus Rift S is connected

### ISSUE THREAD

**Issue by jacobh12349** [dotnet/wpf#9706]
My wpf app isn't used for vr, but when I open a wpf app while my oculus rift s vr headset is connected to my computer, the wpf app crashes with this exception message, I think the wpf app is thinking the oculus rift controllers are a stylus, and it crashes because of that for some reason.

```
Exception thrown: 'System.InvalidCastException' in PresentationCore.dll
System.InvalidCastException: Interface not registered

   at MS.Win32.Penimc.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   at MS.Win32.Penimc.UnsafeNativeMethods.CreatePimcManager()
   at System.Environment.get_StackTrace()
   at MS.Win32.Penimc.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   at MS.Win32.Penimc.UnsafeNativeMethods.CreatePimcManager()
   at MS.Win32.Penimc.UnsafeNativeMethods.get_PimcManager()
   at System.Windows.Input.PenThreadWorker.WorkerOperationGetTabletsInfo.OnDoWork()
   at System.Windows.Input.PenThreadWorker.WorkerOperation.DoWork()
   at System.Windows.Input.PenThreadWorker.ThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by lindexi** [comment]
@jacobh12349 Could you try enable the WMPOINTER by the code:

```csharp
        public App()
        {
            AppContext.SetSwitch("Switch.System.Windows.Input.Stylus.EnablePointerSupport", true);
        }
```

**Comment by jacobh12349** [comment]
> ```cs
> AppContext.SetSwitch("Switch.System.Windows.Input.Stylus.EnablePointerSupport", true);
> ```

I don't want my app to support the rift controllers though, i just have my wpf app running in the background.

**Comment by jacobh12349** [comment]
i also dont have any styluses
