### ISSUE TITLE
Clipboard.SetText fails with CLIPBRD_E_CANT_OPEN

### ISSUE THREAD

**Issue by josefblaha** [dotnet/wpf#9901]
### Description

Most of the time, the call to `Clipboard.SetText` takes several hundred milliseconds and then fails.

### Reproduction Steps

Attempt to copy text to clipboard in a WPF app like this:
```csharp
Clipboard.SetText("text");
```

### Expected behavior

It should place the text in clipboard immediately.

### Actual behavior

Most of the time, it takes several hundred milliseconds and then fails with the following exception:
```
System.Runtime.InteropServices.COMException (0x800401D0): Module OpenClipboard failed (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at WpfCopyTest.MainWindow.CopyButton_OnClick(Object sender, RoutedEventArgs e) in D:\Documents\WpfCopyTest\MainWindow.xaml.cs:line 39
```

### Known Workarounds

The same code using `System.Windows.Forms.Clipboard` instead of `System.Windows.Clipboard` works without a problem.

### Configuration

.NET 8.0.400, Windows 11 23H2, x64

I don't think I have anything unusual installed that would monitor the clipboard and block it.
I tried disabling Windows clipboard history with no effect.

### Other information

It doesn't look like a widespread issue, perhaps it's configuration specific.

Possibly related to #9106.

The reason I'm involved is that I'm trying to fix the clipboard issue in PowerToys: https://github.com/microsoft/PowerToys/issues/25437

**Comment by rampaa** [comment]
I get the same exception while using `Clipboard.SetText`. I'm working around this issue by using `Clipboard.SetDataObject(text, false);` instead, which obviously is not ideal.

**Comment by Symbai** [comment]
> The WinForms implementation works fine. Why is that?

Here is possible answer for this question: https://stackoverflow.com/questions/68666/clipbrd-e-cant-open-error-when-setting-the-clipboard-from-net#comment1287439_69081

**Comment by miloush** [comment]
For reference, here is the retry code in Winforms, one cycle for copy one for flush:

https://github.com/dotnet/winforms/blob/ea461e204bb63903c3bad5786f823d8645d0fe79/src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs#L50C21-L73

By default retryTimes = 10, retryDelay = 100.

**Comment by miloush** [comment]
We do retry as well, same values:

https://github.com/dotnet/wpf/blob/9fe50c794def6cbccb8704eadeb74b492eeb208a/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/clipboard.cs#L484-L515

Not for flush though. Sounds reasonable to do that too.

**Comment by miloush** [comment]
Good reminder to me never trust SO. We retry too, same values, both for set data and flush:

https://github.com/dotnet/wpf/blob/9fe50c794def6cbccb8704eadeb74b492eeb208a/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/clipboard.cs#L484-L515

https://github.com/dotnet/wpf/blob/9fe50c794def6cbccb8704eadeb74b492eeb208a/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/clipboard.cs#L141-L163

**Comment by josefblaha** [comment]
> I get the same exception while using `Clipboard.SetText`. I'm working around this issue by using `Clipboard.SetDataObject(text, false);` instead, which obviously is not ideal.

Yes, that works for me as well. Setting `copy: false` should not retain the clipboard contents when the app exists. However, for some reason it is retained anyway; at least for short strings.

**Comment by rampaa** [comment]
> Setting copy: false should not retain the clipboard contents when the app exists. However, for some reason it is retained anyway; at least for short strings.

For me the text isn't being retained after the app is closed even if the text is quite short.

**Comment by miloush** [comment]
That sounds likes a noteworthy difference. @josefblaha can you check who is calling you with WM_RENDERFORMAT or WM_RENDERALLFORMATS?

**Comment by josefblaha** [comment]
I made a small app to test various methods of copying to clipboard: https://github.com/josefblaha/clipboard-playground

@miloush I'm not sure how to check for the caller. I tried handling the `WM_RENDERFORMAT` message and calling `GetClipboardOwner`. As per docs, when the message is sent, "the clipboard is currently being held open by the application that requested the format to be rendered." However, in my case, it returns my window handle:
![image](https://github.com/user-attachments/assets/86d6048b-9414-46ee-bf64-2720011d1741)

**Comment by miloush** [comment]
`GetOpenClipboardWindow`

**Comment by miloush** [comment]
In fact maybe you could try `GetOpenClipboardWindow` when you get the CLIPBRD_E_CANT_OPEN error.

**Comment by rampaa** [comment]
For the records, I get the `CLIPBRD_E_CANT_OPEN` exception with `Clipboard.GetText()` as well (and I don't know any fancy workaround for this problem, so I just retry till I get the text from clipboard).

I tried calling `GetOpenClipboardWindow` before calling `Clipboard.GetText()` and after getting the `CLIPBRD_E_CANT_OPEN` exception and it just returns 0 for both cases. For reference, here's the related code:

```C#
    private async Task<bool> CopyFromClipboard()
    {
        bool gotTextFromClipboard = false;
        while (Clipboard.ContainsText() && !gotTextFromClipboard)
        {
            try
            {
                Console.WriteLine(WinApi.GetOpenClipboardWindow()); // Prints 0
                string text = Clipboard.GetText();
                gotTextFromClipboard = true;

                return CopyText(text);
            }
            catch (ExternalException ex)
            {
                Console.WriteLine(WinApi.GetOpenClipboardWindow()); // Prints 0
                await Task.Delay(5).ConfigureAwait(true);
            }
        }

        return false;
    }
```

**Comment by josefblaha** [comment]
For me, `GetOpenClipboardWindow()` returns `0` as well. Both after the exception and in `WM_RENDERFORMAT` handler.

What's interesting: as of today, the WPF `SetText` operation in fact places the text in the clipboard, even if it fails. I saw other users reported this behavior before and they then ignored the exception as a workaround, but I'm pretty sure the text was _not_ copied on my machine before. I installed Windows updates this morning, so maybe something got fixed.

With that being said, my current theory is that something is reading contents of the clipboard whenever it's set. Sometimes, it manages to render the data and release the clipboard before the flush or after it. It such cases, the operation succeeds. But sometimes it gets there first and locks the clipboard for a second or more. In those cases, the flush fails.

I wonder how the OLE API set data render until the flush is called. Does it go through WM_RENDERFORMAT message? Maybe the flush kind-of locks itself. Suppose the following sequence:
| My window | Clipboard listener |
|--------|--------|
| OleSetClipboard | |
| | OpenClipboard |
| OleFlushClipboard (fails with CLIPBRD_E_CANT_OPEN) | |
| Thread.Sleep | |
| OleFlushClipboard (fails with CLIPBRD_E_CANT_OPEN) | |
| ... | |
| COMException| |
| WM_RENDERFORMAT handled | |
| | gets its data |
| | CloseClipboard |

**Comment by miloush** [comment]
Then I am afraid this is not going to be easy to figure out without a repro. If you are on Windows 11, I would expect it to behave similar as mine, i.e. the touch keyboard trying to render it, but that does report the handle correctly. Either way it doesn't explain why it would work for WinForms, unless it's just a race condition.

**Comment by h3xds1nz** [comment]
This is becoming a fun problem; I just had `PresentationCore.Tests` fail on WPF build for that exact same reason. I'm on Win10 and last updates I've installed were in April. The only thing that's new is dotnet and Visual Studio on this machine for the past 3 months.

It uses `copy=true` in the test.
```
xUnit.net Console Runner v2.9.0+593e57303e (32-bit .NET 10.0.0-alpha.1.24504.10)
  Discovering: PresentationCore.Tests
  Discovered:  PresentationCore.Tests
  Starting:    PresentationCore.Tests
Unhandled exception. System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at MS.Internal.SecurityHelper.ThrowExceptionForHR(Int32 hr) in C:\Users\somebody\wpf\src\Microsoft.DotNet.Wpf\src\Shared\MS\Internal\SecurityHelper.cs:line 155
   at System.Windows.Clipboard.Flush() in C:\Users\somebody\wpf\src\Microsoft.DotNet.Wpf\src\PresentationCore\System\Windows\clipboard.cs:line 158
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy) in C:\Users\somebody\wpf\src\Microsoft.DotNet.Wpf\src\PresentationCore\System\Windows\clipboard.cs:line 514
   at System.Windows.Clipboard.SetDataObject(Object data, Boolean copy) in C:\Users\somebody\wpf\src\Microsoft.DotNet.Wpf\src\PresentationCore\System\Windows\clipboard.cs:line 442
   at PresentationCore.Tests.BinaryFormat.DataObjectTests.TestLogic(Object value) in C:\Users\somebody\wpf\src\Microsoft.DotNet.Wpf\tests\UnitTests\PresentationCore.Tests\BinaryFormat\DataObjectTests.cs:line 34
   at PresentationCore.Tests.BinaryFormat.DataObjectTests.<>c__DisplayClass0_0.<DataObject_UnSupportedObjects_SetData>b__0() in C:\Users\somebody\wpf\src\Microsoft.DotNet.Wpf\tests\UnitTests\PresentationCore.Tests\BinaryFormat\DataObjectTests.cs:line 21
   at System.Threading.Thread.StartCallback()
```

**Comment by josefblaha** [comment]
In the search of the mysterious clipboard listener, I also tried to call `SetClipboardViewer`, which is the oldest way to monitor clipboard contents in Win32 API. It should return the HWND of the next viewer in a global clipboard viewer chain. Unfortunately, it returned 0.

**Comment by josefblaha** [comment]
I got some time during holidays to investigate more and I found something.

## Short story

On my machine, the error is triggered because of ESET Internet Security antivirus software. The workaround is to disable "clipboard protection" in its secure browser settings.

The question of why the WPF version is affected and the Windows Forms not still remains.

## Long story

### Investigation

The goal was to find out who's reading the clipboard content after the copy operation. As the `GetOpenClipboardWindow()` returned zero, there was no easy way to find the mysterious listener.

I used a trick (and I'm a little bit proud of it 😛 ) - copy a string of a billion characters and look which processes are using a lot of CPU and memory afterward.

A process `eOPPFrame.exe` was among the most active. It's "ESET Online payment protection frame," a part of [ESET Internet Security](https://en.wikipedia.org/wiki/ESET_NOD32) suite. This software contains features to protect an Internet browser process and its data. One of the features is "clipboard protection," which prevents placing any sensitive data (like credit card numbers) into
clipboard. Apparently, it makes sure no other process sees the clipboard content while it's checking it.

Disabling the secure browser or the clipboard protection feature alone makes the error go away.

### Windows clipboard history

Even with the security feature disabled, the clipboard was still monitored and its content immediately rendered. This time, however, `GetOpenClipboardWindow()` returned a valid HWND, which belonged to `svchost.exe` process
running from command line `C:\WINDOWS\system32\svchost.exe -k ClipboardSvcGroup -p -s cbdhsvc`. This is a Windows service managing clipboard history.

Disabling clipboard history in Windows settings makes the immediate clipboard content rendering go away.

One thing to note is that, with clipboard history enabled, I'm still able to trigger the error by making tens of `SetText` calls in sequence. With history disabled, I couldn't reproduce it at all.
@h3xds1nz, that could be the case of your test suite.

### WPF vs. Windows Forms
IMHO, the next step to investigate should be why there is the difference between the WPF and Windows Forms version. They both use the same OLE API.

One clear difference is the usage of `OleServicesContext` in the WPF version.

**Comment by miloush** [comment]
Nice trick! The WPF vs WF might be just a timing difference.

**Comment by h3xds1nz** [comment]
AVs, always causing the weirdest of problems, haha. Nice trick, as miloush said.

Anyways, in my case the Clipboard history was disabled (and so are all AVs, incl. Defender),  so it seems like the cause besides the fact all Clipboard operations are one big race condition, is unfortunately still unknown. Not really keen on it, happened once after all.

**Comment by daviewales** [comment]
> The goal was to find out who's reading the clipboard content after the copy operation. As the `GetOpenClipboardWindow()` returned zero, there was no easy way to find the mysterious listener.
> 
> I used a trick (and I'm a little bit proud of it 😛 ) - copy a string of a billion characters and look which processes are using a lot of CPU and memory afterward.

Using this trick, I found that this issue may also be caused by `msrdc.exe`, which is used by Windows Subsystem for Linux (WSL) to display GUI windows with WSLg.

Instructing WSLg to [use MSTSC instead of msrdc](https://github.com/microsoft/wslg/issues/901#issuecomment-1335757205) and restarting WSL fixes the issue for me.

``` config
# ~/.wslgconfig
[system-distro-env]
WSLG_USE_MSTSC=true
```

Note that the config above is `~/.wslgconfig`, NOT `~/.wslconfig`!
